### ISSUE TITLE
Flaky master: perf test

### ISSUE THREAD

**Issue by garyverhaegen-da** [digital-asset/daml#1011]
[This build](https://dev.azure.com/digitalasset/daml/_build/results?buildId=4739) of [this commit](https://github.com/digital-asset/daml/commit/094878938683c470ea232072f83e13bfd86015f1) on master failed the perf test. Logs are a bit verbose so I don't have much to add yet. @bitonic can you get someone on the runtime side to take a look?

**Comment by bitonic** [comment]
@gaboraranyossy-da can you take a look at this?

**Comment by bitonic** [comment]
relevant parts of the log:

```
2019-05-08T13:42:40.3578534Z java.util.concurrent.TimeoutException: Futures timed out after [5 minutes]
2019-05-08T13:42:40.3580625Z    at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
2019-05-08T13:42:40.3581300Z    at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:259)
2019-05-08T13:42:40.3582060Z    at scala.concurrent.Await$.$anonfun$result$1(package.scala:215)
2019-05-08T13:42:40.3582431Z    at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
2019-05-08T13:42:40.3582835Z    at scala.concurrent.Await$.result(package.scala:142)
2019-05-08T13:42:40.3583263Z    at com.digitalasset.platform.sandbox.perf.LargeTransactionBench.manySmallContracts(LargeTransactionBench.scala:57)
2019-05-08T13:42:40.3583707Z    at com.digitalasset.platform.sandbox.perf.generated.LargeTransactionBench_manySmallContracts_jmhTest.manySmallContracts_avgt_jmhStub(LargeTransactionBench_manySmallContracts_jmhTest.java:451)
2019-05-08T13:42:40.3584404Z    at com.digitalasset.platform.sandbox.perf.generated.LargeTransactionBench_manySmallContracts_jmhTest.manySmallContracts_AverageTime(LargeTransactionBench_manySmallContracts_jmhTest.java:332)
2019-05-08T13:42:40.3593621Z    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2019-05-08T13:42:40.3594272Z    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2019-05-08T13:42:40.3594634Z    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2019-05-08T13:42:40.3595482Z    at java.lang.reflect.Method.invoke(Method.java:498)
2019-05-08T13:42:40.3611637Z    at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:453)
2019-05-08T13:42:40.3612809Z    at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:437)
2019-05-08T13:42:40.3613642Z    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-05-08T13:42:40.3614148Z    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2019-05-08T13:42:40.3614498Z    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-05-08T13:42:40.3615063Z    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2019-05-08T13:42:40.3615384Z    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2019-05-08T13:42:40.3615731Z    at java.lang.Thread.run(Thread.java:748)
```
