### ISSUE TITLE
Flaky master: //ledger/ledger-api-integration-tests:ledger-api-integration-tests_test_suite_src_test_itsuite_scala_com_digitalasset_platform_tests_integration_ledger_api_commands_CommandServiceBackPressureIT.scala

### ISSUE THREAD

**Issue by garyverhaegen-da** [digital-asset/daml#1012]
[This build](https://dev.azure.com/digitalasset/daml/_build/results?buildId=4727) of [this commit](https://github.com/digital-asset/daml/commit/a23000446bf1014c4d56fc10514755249e2e4e45) on master failed. @bitonic from the test name it looks like a runtime test. Can you get someone to look into it?

**Comment by bitonic** [comment]
@gaboraranyossy-da can you take a look at this?

**Comment by bitonic** [comment]
relevant part of the logs:

```
  - should reject requests with RESOURCE_EXHAUSTED *** FAILED *** (2 seconds, 393 milliseconds)
    com.digitalasset.platform.apitesting.MultiFixtureBase$$anon$1: Test failed on fixture SandboxSql with class org.scalatest.exceptions.TestFailedException: Vector() was empty
    Cause: org.scalatest.exceptions.TestFailedException: Vector() was empty
    at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:346)
    at org.scalatest.words.ResultOfNotWordForAny.be(ResultOfNotWordForAny.scala:670)
    at com.digitalasset.platform.tests.integration.ledger.api.commands.CommandServiceBackPressureIT$$anonfun$$nestedInanonfun$new$3$1.$anonfun$applyOrElse$5(CommandServiceBackPressureIT.scala:71)
    at scala.util.Success.$anonfun$map$1(Try.scala:251)
    at scala.util.Success.map(Try.scala:209)
    at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
    at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
    at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
    at org.scalatest.concurrent.SerialExecutionContext.recRunNow(SerialExecutionContext.scala:120)
    at org.scalatest.concurrent.SerialExecutionContext.runNow(SerialExecutionContext.scala:111)
    at org.scalatest.AsyncSuperEngine.runTestImpl(AsyncEngine.scala:295)
    at org.scalatest.AsyncWordSpecLike.runTest(AsyncWordSpecLike.scala:1074)
    at org.scalatest.AsyncWordSpecLike.runTest$(AsyncWordSpecLike.scala:1055)
    at org.scalatest.AsyncWordSpec.runTest(AsyncWordSpec.scala:2294)
    at org.scalatest.AsyncWordSpecLike.$anonfun$runTests$1(AsyncWordSpecLike.scala:1133)
    at org.scalatest.AsyncSuperEngine.$anonfun$runTestsInBranch$1(AsyncEngine.scala:434)
    at scala.collectio  - should reject requests with RESOURCE_EXHAUSTED *** FAILED *** (2 seconds, 393 milliseconds)
    com.digitalasset.platform.apitesting.MultiFixtureBase$$anon$1: Test failed on fixture SandboxSql with class org.scalatest.exceptions.TestFailedException: Vector() was empty
    Cause: org.scalatest.exceptions.TestFailedException: Vector() was empty
    at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:346)
    at org.scalatest.words.ResultOfNotWordForAny.be(ResultOfNotWordForAny.scala:670)
    at com.digitalasset.platform.tests.integration.ledger.api.commands.CommandServiceBackPressureIT$$anonfun$$nestedInanonfun$new$3$1.$anonfun$applyOrElse$5(CommandServiceBackPressureIT.scala:71)
    at scala.util.Success.$anonfun$map$1(Try.scala:251)
    at scala.util.Success.map(Try.scala:209)
    at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
    at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
    at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
    at org.scalatest.concurrent.SerialExecutionContext.recRunNow(SerialExecutionContext.scala:120)
    at org.scalatest.concurrent.SerialExecutionContext.runNow(SerialExecutionContext.scala:111)
    at org.scalatest.AsyncSuperEngine.runTestImpl(AsyncEngine.scala:295)
    at org.scalatest.AsyncWordSpecLike.runTest(AsyncWordSpecLike.scala:1074)
    at org.scalatest.AsyncWordSpecLike.runTest$(AsyncWordSpecLike.scala:1055)
    at org.scalatest.AsyncWordSpec.runTest(AsyncWordSpec.scala:2294)
    at org.scalatest.AsyncWordSpecLike.$anonfun$runTests$1(AsyncWordSpecLike.scala:1133)
    at org.scalatest.AsyncSuperEngine.$anonfun$runTestsInBranch$1(AsyncEngine.scala:434)
    at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
    at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
    at scala.collection.immutable.List.foldLeft(List.scala:86)
    at org.scalatest.AsyncSuperEngine.traverseSubNodes$1(AsyncEngine.scala:419)
    at org.scalatest.AsyncSuperEngine.runTestsInBranch(AsyncEngine.scala:475)
    at org.scalatest.AsyncSuperEngine.$anonfun$runTestsInBranch$1(AsyncEngine.scala:460)
    at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
    at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
    at scala.collection.immutable.List.foldLeft(List.scala:86)
    at org.scalatest.AsyncSuperEngine.traverseSubNodes$1(AsyncEngine.scala:419)
    at org.scalatest.AsyncSuperEngine.runTestsInBranch(AsyncEngine.scala:475)
    at org.scalatest.AsyncSuperEngine.$anonfun$runTestsInBranch$1(AsyncEngine.scala:460)
    at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
    at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
    at scala.collection.immutable.List.foldLeft(List.scala:86)
    at org.scalatest.AsyncSuperEngine.traverseSubNodes$1(AsyncEngine.scala:419)
    at org.scalatest.AsyncSuperEngine.runTestsInBranch(AsyncEngine.scala:483)
    at org.scalatest.AsyncSuperEngine.runTestsImpl(AsyncEngine.scala:550)
    at org.scalatest.AsyncWordSpecLike.runTests(AsyncWordSpecLike.scala:1133)
    at org.scalatest.AsyncWordSpecLike.runTests$(AsyncWordSpecLike.scala:1132)
    at org.scalatest.AsyncWordSpec.runTests(AsyncWordSpec.scala:2294)
    at org.scalatest.Suite.run(Suite.scala:1147)
    at org.scalatest.Suite.run$(Suite.scala:1129)
    at org.scalatest.AsyncWordSpec.org$scalatest$AsyncWordSpecLike$$super$run(AsyncWordSpec.scala:2294)
    at org.scalatest.AsyncWordSpecLike.$anonfun$run$1(AsyncWordSpecLike.scala:1178)
    at org.scalatest.AsyncSuperEngine.runImpl(AsyncEngine.scala:620)
    at org.scalatest.AsyncWordSpecLike.run(AsyncWordSpecLike.scala:1178)
    at org.scalatest.AsyncWordSpecLike.run$(AsyncWordSpecLike.scala:1176)
    at com.digitalasset.platform.tests.integration.ledger.api.commands.CommandServiceBackPressureIT.org$scalatest$BeforeAndAfterAll$$super$run(CommandServiceBackPressureIT.scala:26)
    at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
    at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
    at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
    at com.digitalasset.platform.tests.integration.ledger.api.commands.CommandServiceBackPressureIT.run(CommandServiceBackPressureIT.scala:26)
    at org.scalatest.Suite.callExecuteOnSuite$1(Suite.scala:1210)
    at org.scalatest.Suite.$anonfun$runNestedSuites$1(Suite.scala:1257)
    at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
    at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:194)
    at org.scalatest.Suite.runNestedSuites(Suite.scala:1255)
    at org.scalatest.Suite.runNestedSuites$(Suite.scala:1189)
    at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:30)
    at org.scalatest.Suite.run(Suite.scala:1144)
    at org.scalatest.Suite.run$(Suite.scala:1129)
    at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:30)
    at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
    at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1346)
    at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1340)
    at scala.collection.immutable.List.foreach(List.scala:389)
    at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1340)
    at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1031)
    at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1010)
    at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1506)
    at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
    at org.scalatest.tools.Runner$.main(Runner.scala:827)
    at org.scalatest.tools.Runner.main(Runner.scala)
    at io.bazel.rulesscala.scala_test.Runner.main(Runner.java:30)
    + 0 requests failed with Status{code=RESOURCE_EXHAUSTED, description=null, cause=null} 
n.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
    at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
    at scala.collection.immutable.List.foldLeft(List.scala:86)
    at org.scalatest.AsyncSuperEngine.traverseSubNodes$1(AsyncEngine.scala:419)
    at org.scalatest.AsyncSuperEngine.runTestsInBranch(AsyncEngine.scala:475)
    at org.scalatest.AsyncSuperEngine.$anonfun$runTestsInBranch$1(AsyncEngine.scala:460)
    at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
    at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
    at scala.collection.immutable.List.foldLeft(List.scala:86)
    at org.scalatest.AsyncSuperEngine.traverseSubNodes$1(AsyncEngine.scala:419)
    at org.scalatest.AsyncSuperEngine.runTestsInBranch(AsyncEngine.scala:475)
    at org.scalatest.AsyncSuperEngine.$anonfun$runTestsInBranch$1(AsyncEngine.scala:460)
    at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
    at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
    at scala.collection.immutable.List.foldLeft(List.scala:86)
    at org.scalatest.AsyncSuperEngine.traverseSubNodes$1(AsyncEngine.scala:419)
    at org.scalatest.AsyncSuperEngine.runTestsInBranch(AsyncEngine.scala:483)
    at org.scalatest.AsyncSuperEngine.runTestsImpl(AsyncEngine.scala:550)
    at org.scalatest.AsyncWordSpecLike.runTests(AsyncWordSpecLike.scala:1133)
    at org.scalatest.AsyncWordSpecLike.runTests$(AsyncWordSpecLike.scala:1132)
    at org.scalatest.AsyncWordSpec.runTests(AsyncWordSpec.scala:2294)
    at org.scalatest.Suite.run(Suite.scala:1147)
    at org.scalatest.Suite.run$(Suite.scala:1129)
    at org.scalatest.AsyncWordSpec.org$scalatest$AsyncWordSpecLike$$super$run(AsyncWordSpec.scala:2294)
    at org.scalatest.AsyncWordSpecLike.$anonfun$run$1(AsyncWordSpecLike.scala:1178)
    at org.scalatest.AsyncSuperEngine.runImpl(AsyncEngine.scala:620)
    at org.scalatest.AsyncWordSpecLike.run(AsyncWordSpecLike.scala:1178)
    at org.scalatest.AsyncWordSpecLike.run$(AsyncWordSpecLike.scala:1176)
    at com.digitalasset.platform.tests.integration.ledger.api.commands.CommandServiceBackPressureIT.org$scalatest$BeforeAndAfterAll$$super$run(CommandServiceBackPressureIT.scala:26)
    at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
    at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
    at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
    at com.digitalasset.platform.tests.integration.ledger.api.commands.CommandServiceBackPressureIT.run(CommandServiceBackPressureIT.scala:26)
    at org.scalatest.Suite.callExecuteOnSuite$1(Suite.scala:1210)
    at org.scalatest.Suite.$anonfun$runNestedSuites$1(Suite.scala:1257)
    at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
    at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:194)
    at org.scalatest.Suite.runNestedSuites(Suite.scala:1255)
    at org.scalatest.Suite.runNestedSuites$(Suite.scala:1189)
    at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:30)
    at org.scalatest.Suite.run(Suite.scala:1144)
    at org.scalatest.Suite.run$(Suite.scala:1129)
    at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:30)
    at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
    at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1346)
    at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1340)
    at scala.collection.immutable.List.foreach(List.scala:389)
    at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1340)
    at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1031)
    at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1010)
    at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1506)
    at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
    at org.scalatest.tools.Runner$.main(Runner.scala:827)
    at org.scalatest.tools.Runner.main(Runner.scala)
    at io.bazel.rulesscala.scala_test.Runner.main(Runner.java:30)
    + 0 requests failed with Status{code=RESOURCE_EXHAUSTED, description=null, cause=null} 
```
