### ISSUE TITLE
Flakiness in Java bot tests

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#10273]
Occasionally those tests fail with
```
2021-07-13T17:52:17.5512375Z Run starting. Expected test count is: 5
2021-07-13T17:52:17.5513930Z BotTest:
2021-07-13T17:52:17.5516048Z Bot
2021-07-13T17:52:17.5518089Z - should create a flowable of WorkflowEvents from the ACS (276 milliseconds)
2021-07-13T17:52:17.5522324Z - should create a flowable of WorkflowEvents from the transactions (150 milliseconds)
2021-07-13T17:52:17.5524640Z ERROR c.daml.ledger.rxjava.components.Bot - Error submitting commands commandId_1 for party Alice: expected failure
2021-07-13T17:52:17.5526793Z ERROR c.daml.ledger.rxjava.components.Bot - Error submitting commands commandId_2 for party Alice: expected failure
2021-07-13T17:52:17.5528835Z ERROR c.daml.ledger.rxjava.components.Bot - Error submitting commands commandId_3 for party Alice: expected failure
2021-07-13T17:52:17.5536709Z - should handle submission failures non-fatally (210 milliseconds)
2021-07-13T17:52:17.5559858Z - should wire a bot to the ledger-client *** FAILED *** (238 milliseconds)
2021-07-13T17:52:17.5566676Z   ArrayBuffer(SubmitCommandsRequest{workflowId='wid', applicationId='test-app-id', commandId='commandId_1', party='Alice', minLedgerTimeAbs=Optional.empty, minLedgerTimeRel=Optional.empty, deduplicationTime=Optional.empty, commands=[ExerciseCommand{templateId=Identifier{packageId='pid', moduleName='mname', entityName='ename'}, contractId='cid_-832753514', choice='choice', choiceArgument=Unit{}}]}, SubmitCommandsRequest{workflowId='wid', applicationId='test-app-id', commandId='commandId_2', party='Alice', minLedgerTimeAbs=Optional.empty, minLedgerTimeRel=Optional.empty, deduplicationTime=Optional.empty, commands=[ExerciseCommand{templateId=Identifier{packageId='pid', moduleName='mname', entityName='ename'}, contractId='cid_-1165539236', choice='choice', choiceArgument=Unit{}}]}, SubmitCommandsRequest{workflowId='wid', applicationId='test-app-id', commandId='commandId_3', party='Alice', minLedgerTimeAbs=Optional.empty, minLedgerTimeRel=Optional.empty, deduplicationTime=Optional.empty, commands=[ExerciseCommand{templateId=Identifier{packageId='pid', moduleName='mname', entityName='ename'}, contractId='cid_1957572804', choice='choice', choiceArgument=Unit{}}]}, SubmitCommandsRequest{workflowId='wid', applicationId='test-app-id', commandId='commandId_4', party='Alice', minLedgerTimeAbs=Optional.empty, minLedgerTimeRel=Optional.empty, deduplicationTime=Optional.empty, commands=[ExerciseCommand{templateId=Identifier{packageId='pid', moduleName='mname', entityName='ename'}, contractId='cid_-1165539236', choice='choice', choiceArgument=Unit{}}]}, SubmitCommandsRequest{workflowId='wid', applicationId='test-app-id', commandId='commandId_5', party='Alice', minLedgerTimeAbs=Optional.empty, minLedgerTimeRel=Optional.empty, deduplicationTime=Optional.empty, commands=[ExerciseCommand{templateId=Identifier{packageId='pid', moduleName='mname', entityName='ename'}, contractId='cid_1957572804', choice='choice', choiceArgument=Unit{}}]}) had size 5 instead of expected size 3 (BotTest.scala:418)
2021-07-13T17:52:17.5593214Z   org.scalatest.exceptions.TestFailedException:
2021-07-13T17:52:17.5594371Z   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
2021-07-13T17:52:17.5595619Z   at org.scalatest.matchers.should.Matchers$ResultOfHaveWordForExtent.size(Matchers.scala:2720)
2021-07-13T17:52:17.5596577Z   at com.daml.ledger.rxjava.components.BotTest.$anonfun$new$8(BotTest.scala:418)
2021-07-13T17:52:17.5597608Z   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
2021-07-13T17:52:17.5598522Z   at com.daml.ledger.rxjava.components.BotTest$.com$daml$ledger$rxjava$components$BotTest$$using(BotTest.scala:639)
2021-07-13T17:52:17.5599444Z   at com.daml.ledger.rxjava.components.BotTest.$anonfun$new$7(BotTest.scala:383)
2021-07-13T17:52:17.5600336Z   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
2021-07-13T17:52:17.5601211Z   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
2021-07-13T17:52:17.5601905Z   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
2021-07-13T17:52:17.5602658Z   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
2021-07-13T17:52:17.5603348Z   at org.scalatest.Transformer.apply(Transformer.scala:22)
2021-07-13T17:52:17.5604055Z   at org.scalatest.Transformer.apply(Transformer.scala:20)
2021-07-13T17:52:17.5604795Z   at org.scalatest.flatspec.AnyFlatSpecLike$$anon$5.apply(AnyFlatSpecLike.scala:1683)
2021-07-13T17:52:17.5605677Z   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
2021-07-13T17:52:17.5606351Z   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
2021-07-13T17:52:17.5607276Z   at org.scalatest.flatspec.AnyFlatSpec.withFixture(AnyFlatSpec.scala:1685)
2021-07-13T17:52:17.5608191Z   at org.scalatest.flatspec.AnyFlatSpecLike.invokeWithFixture$1(AnyFlatSpecLike.scala:1681)
2021-07-13T17:52:17.5609073Z   at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTest$1(AnyFlatSpecLike.scala:1693)
2021-07-13T17:52:17.5609892Z   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
2021-07-13T17:52:17.5610632Z   at org.scalatest.flatspec.AnyFlatSpecLike.runTest(AnyFlatSpecLike.scala:1693)
2021-07-13T17:52:17.5611418Z   at org.scalatest.flatspec.AnyFlatSpecLike.runTest$(AnyFlatSpecLike.scala:1675)
2021-07-13T17:52:17.5612161Z   at org.scalatest.flatspec.AnyFlatSpec.runTest(AnyFlatSpec.scala:1685)
2021-07-13T17:52:17.5612980Z   at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTests$1(AnyFlatSpecLike.scala:1751)
2021-07-13T17:52:17.5613780Z   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
2021-07-13T17:52:17.5614500Z   at scala.collection.immutable.List.foreach(List.scala:333)
2021-07-13T17:52:17.5615263Z   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
2021-07-13T17:52:17.5616016Z   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
2021-07-13T17:52:17.5616878Z   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
2021-07-13T17:52:17.5617820Z   at scala.collection.immutable.List.foreach(List.scala:333)
2021-07-13T17:52:17.5618557Z   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
2021-07-13T17:52:17.5619459Z   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
2021-07-13T17:52:17.5620711Z   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
2021-07-13T17:52:17.5621626Z   at org.scalatest.flatspec.AnyFlatSpecLike.runTests(AnyFlatSpecLike.scala:1751)
2021-07-13T17:52:17.5623416Z   at org.scalatest.flatspec.AnyFlatSpecLike.runTests$(AnyFlatSpecLike.scala:1750)
2021-07-13T17:52:17.5624357Z   at org.scalatest.flatspec.AnyFlatSpec.runTests(AnyFlatSpec.scala:1685)
2021-07-13T17:52:17.5625682Z   at org.scalatest.Suite.run(Suite.scala:1112)
2021-07-13T17:52:17.5626346Z   at org.scalatest.Suite.run$(Suite.scala:1094)
2021-07-13T17:52:17.5627869Z   at org.scalatest.flatspec.AnyFlatSpec.org$scalatest$flatspec$AnyFlatSpecLike$$super$run(AnyFlatSpec.scala:1685)
2021-07-13T17:52:17.5628833Z   at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$run$1(AnyFlatSpecLike.scala:1796)
2021-07-13T17:52:17.5629583Z   at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
2021-07-13T17:52:17.5630749Z   at org.scalatest.flatspec.AnyFlatSpecLike.run(AnyFlatSpecLike.scala:1796)
2021-07-13T17:52:17.5632203Z   at org.scalatest.flatspec.AnyFlatSpecLike.run$(AnyFlatSpecLike.scala:1794)
2021-07-13T17:52:17.5633940Z   at org.scalatest.flatspec.AnyFlatSpec.run(AnyFlatSpec.scala:1685)
2021-07-13T17:52:17.5635050Z   at org.scalatest.Suite.callExecuteOnSuite$1(Suite.scala:1175)
2021-07-13T17:52:17.5635803Z   at org.scalatest.Suite.$anonfun$runNestedSuites$1(Suite.scala:1222)
2021-07-13T17:52:17.5636602Z   at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
2021-07-13T17:52:17.5637927Z   at org.scalatest.Suite.runNestedSuites(Suite.scala:1220)
2021-07-13T17:52:17.5639417Z   at org.scalatest.Suite.runNestedSuites$(Suite.scala:1154)
2021-07-13T17:52:17.5640520Z   at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:30)
2021-07-13T17:52:17.5641844Z   at org.scalatest.Suite.run(Suite.scala:1109)
2021-07-13T17:52:17.5642703Z   at org.scalatest.Suite.run$(Suite.scala:1094)
2021-07-13T17:52:17.5643750Z   at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:30)
2021-07-13T17:52:17.5644946Z   at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
2021-07-13T17:52:17.5646192Z   at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1320)
2021-07-13T17:52:17.5647308Z   at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1314)
2021-07-13T17:52:17.5648349Z   at scala.collection.immutable.List.foreach(List.scala:333)
2021-07-13T17:52:17.5649502Z   at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1314)
2021-07-13T17:52:17.5650268Z   at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:993)
2021-07-13T17:52:17.5651890Z   at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:971)
2021-07-13T17:52:17.5652719Z   at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1480)
2021-07-13T17:52:17.5653532Z   at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
2021-07-13T17:52:17.5654219Z   at org.scalatest.tools.Runner$.main(Runner.scala:775)
2021-07-13T17:52:17.5655266Z   at org.scalatest.tools.Runner.main(Runner.scala)
2021-07-13T17:52:17.5656428Z   at io.bazel.rulesscala.scala_test.Runner.main(Runner.java:34)
2021-07-13T17:52:17.5657951Z - should query first the ACS and then the LedgerEnd sequentially so that there is not race condition and LedgerEnd >= ACS offset (1 second, 32 milliseconds)
```

**Comment by tudor-da** [comment]
Encountered the same failure as above, but on a previous occurrence of the assertion
```
Run starting. Expected test count is: 5
BotTest:
Bot
- should create a flowable of WorkflowEvents from the ACS (391 milliseconds)
  at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$run$1(AnyFlatSpecLike.scala:1796)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
  at org.scalatest.flatspec.AnyFlatSpecLike.run(AnyFlatSpecLike.scala:1796)
  at org.scalatest.flatspec.AnyFlatSpecLike.run$(AnyFlatSpecLike.scala:1794)
  at org.scalatest.flatspec.AnyFlatSpec.run(AnyFlatSpec.scala:1685)
  at org.scalatest.Suite.callExecuteOnSuite$1(Suite.scala:1175)
  at org.scalatest.Suite.$anonfun$runNestedSuites$1(Suite.scala:1222)
  at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
  at org.scalatest.Suite.runNestedSuites(Suite.scala:1220)
  at org.scalatest.Suite.runNestedSuites$(Suite.scala:1154)
  at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:30)
  at org.scalatest.Suite.run(Suite.scala:1109)
  at org.scalatest.Suite.run$(Suite.scala:1094)
  at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:30)
  at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
  at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1320)
  at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1314)
  at scala.collection.immutable.List.foreach(List.scala:333)
  at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1314)
  at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:993)
  at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:971)
  at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1480)
  at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
  at org.scalatest.tools.Runner$.main(Runner.scala:775)
  at org.scalatest.tools.Runner.main(Runner.scala)
  at io.bazel.rulesscala.scala_test.Runner.main(Runner.java:34)
- should query first the ACS and then the LedgerEnd sequentially so that there is not race condition and LedgerEnd >= ACS offset (1 second, 984 milliseconds)
Run completed in 9 seconds, 344 milliseconds.
Total number of tests run: 5
Suites: completed 2, aborted 0
Tests: succeeded 4, failed 1, canceled 0, ignored 0, pending 0
*** 1 TEST FAILED ***
```

**Comment by cocreature** [comment]
So as far as I can tell the following is happening:
1. The test sends a create which is picked up by the bot.
2. The bot sends a command based on that contract. This asynchronously modifies active contracts & the pending set but not immediately.
3. The sent command is enough to unblock the test which sends a transaction which archives this contract and creates two new contracts. This triggers the bot to send two commands again adding things to the pending set asynchronously.
4. Now the pending set is modified based on the first command. At this point things are already broken I believe. The contract is no longer active which results in us adding a mapping from the contract id to `null` in the pending set which is at least questionable. This also triggers the bot again with the contracts not yet being part of the pending set and this is why we get two extra commands.

It seems like this is fundamentally broken. The pending set should be modified synchronously otherwise you will keep running in this garbage.
5.

**Comment by cocreature** [comment]
Given that the java bots are deprecated I’m somewhat tempted to take the easy way out and block until the pending set is updated in the test instead of fixing the bug.

**Comment by stefanobaghino-da** [comment]
The bots have been removed with Daml 2.0, closing.
