### ISSUE TITLE
Scala codegen CLI fails when package name is not provided

### ISSUE THREAD

**Issue by leo-da** [digital-asset/daml#1088]
According to the help, `package-prefix` is optional:
```
$ java -jar codegen-main-100.12.17.jar scala --help
codegen 100.12.17
Usage: codegen [options] <DAR-file[=package-prefix]>...

Code generator for the DAML ledger bindings.

  <DAR-file[=package-prefix]>...
                           DAR file to use as input of the codegen with an optional, but recommend, package prefix for the generated sources.
  -o, --output-directory <value>
                           Output directory for the generated sources
  -d, --decoderClass <value>
                           Fully Qualified Class Name of the optional Decoder utility
  -V, --verbosity <value>  Verbosity between 0 (only show errors) and 4 (show all messages) -- defaults to 0
  --help                   This help text
```
However running it without the package name ends with an error:
```
$ java -jar codegen-main-100.12.17.jar scala ./quickstart-scala.dar     --output-directory=./codegen-out --verbosity=2
[INFO ] Scala Codegen verbosity: INFO
Exception in thread "main" java.lang.IllegalStateException: Scala Codegen expects all dars mapped to the same package name, requested: {/home/leos/Downloads/project/./quickstart-scala.dar->None,}
	at com.digitalasset.codegen.Main$.darsAndOnePackageName(Main.scala:59)
	at com.digitalasset.codegen.Main$.main(Main.scala:26)
	at com.digitalasset.codegen.CodegenMain$.main(CodegenMain.scala:17)
	at com.digitalasset.codegen.CodegenMain.main(CodegenMain.scala)
```

Also verify if Scala codegen makes use of `--decoderClass` parameter. Remove it if codegen does not do anything with it.

**Comment by stewSquared** [comment]
Is this still relevant? I'm under the impression we only use java codegen now.

**Comment by stefanobaghino-da** [comment]
A good question. The Scala codegen is still used internally, in particular for the Ledger API Test Tool (the aptly named harness that tests the surface of a Ledger API implementation). Maybe in other places as well, but I'm not sure. I would probably keep this around as a reminder for internal users until we refine and work on https://github.com/digital-asset/daml/issues/13159.

**Comment by stefanobaghino-da** [comment]
@stewSquared Ah, I had a second look at this ticket and you were actually right. This is not about the Scala codegen in general but about its CLI. Closing.
