### ISSUE TITLE
Java bindings: CommandSubmissionClientImplTest is flaky

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#10920]
```//language-support/java/bindings-rxjava:bindings-java-tests_test_suite_src_test_scala_com_daml_ledger_rxjava_grpc_CommandSubmissionClientImplTest.scala```

Relevant test output:
```
==================== Test output for //language-support/java/bindings-rxjava:bindings-java-tests_test_suite_src_test_scala_com_daml_ledger_rxjava_grpc_CommandSubmissionClientImplTest.scala (run 1 of 8):
Discovery starting.
Discovery completed in 866 milliseconds.
Run starting. Expected test count is: 6
CommandSubmissionClientImplTest:
[3.1] CommandSubmissionClientImpl.submit
- should timeout should work as expected across calls *** FAILED *** (2 seconds, 166 milliseconds)
  The first command should be stuck The Option on which value was invoked was not defined. (CommandSubmissionClientImplTest.scala:59)
  org.scalatest.exceptions.TestFailedException:
  at org.scalatest.OptionValues$Valuable.value(OptionValues.scala:114)
  at com.daml.ledger.rxjava.grpc.CommandSubmissionClientImplTest.$anonfun$new$3(CommandSubmissionClientImplTest.scala:59)
  at org.scalatest.Assertions.withClue(Assertions.scala:1065)
  at org.scalatest.Assertions.withClue$(Assertions.scala:1052)
  at org.scalatest.flatspec.AnyFlatSpec.withClue(AnyFlatSpec.scala:1685)
  at com.daml.ledger.rxjava.grpc.CommandSubmissionClientImplTest.$anonfun$new$2(CommandSubmissionClientImplTest.scala:46)
  at com.daml.ledger.rxjava.grpc.helpers.LedgerServices.$anonfun$withCommandSubmissionClient$1(LedgerServices.scala:131)
  at com.daml.ledger.rxjava.grpc.helpers.LedgerServices.$anonfun$withServerAndChannel$1(LedgerServices.scala:75)
  at com.daml.ledger.rxjava.grpc.helpers.LedgerServices.withServer(LedgerServices.scala:59)
  at com.daml.ledger.rxjava.grpc.helpers.LedgerServices.withServerAndChannel(LedgerServices.scala:70)
  at com.daml.ledger.rxjava.grpc.helpers.LedgerServices.withCommandSubmissionClient(LedgerServices.scala:130)
  at com.daml.ledger.rxjava.grpc.CommandSubmissionClientImplTest.$anonfun$new$1(CommandSubmissionClientImplTest.scala:43)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.flatspec.AnyFlatSpecLike$$anon$5.apply(AnyFlatSpecLike.scala:1683)
  at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
  at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
  at org.scalatest.flatspec.AnyFlatSpec.withFixture(AnyFlatSpec.scala:1685)
  at org.scalatest.flatspec.AnyFlatSpecLike.invokeWithFixture$1(AnyFlatSpecLike.scala:1681)
  at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTest$1(AnyFlatSpecLike.scala:1693)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
  at org.scalatest.flatspec.AnyFlatSpecLike.runTest(AnyFlatSpecLike.scala:1693)
  at org.scalatest.flatspec.AnyFlatSpecLike.runTest$(AnyFlatSpecLike.scala:1675)
  at org.scalatest.flatspec.AnyFlatSpec.runTest(AnyFlatSpec.scala:1685)
  at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTests$1(AnyFlatSpecLike.scala:1751)
  at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
  at scala.collection.immutable.List.foreach(List.scala:333)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
  at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
  at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
  at scala.collection.immutable.List.foreach(List.scala:333)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
  at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
  at org.scalatest.flatspec.AnyFlatSpecLike.runTests(AnyFlatSpecLike.scala:1751)
  at org.scalatest.flatspec.AnyFlatSpecLike.runTests$(AnyFlatSpecLike.scala:1750)
  at org.scalatest.flatspec.AnyFlatSpec.runTests(AnyFlatSpec.scala:1685)
  at org.scalatest.Suite.run(Suite.scala:1112)
  at org.scalatest.Suite.run$(Suite.scala:1094)
  at org.scalatest.flatspec.AnyFlatSpec.org$scalatest$flatspec$AnyFlatSpecLike$$super$run(AnyFlatSpec.scala:1685)
  at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$run$1(AnyFlatSpecLike.scala:1796)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
  at org.scalatest.flatspec.AnyFlatSpecLike.run(AnyFlatSpecLike.scala:1796)
  at org.scalatest.flatspec.AnyFlatSpecLike.run$(AnyFlatSpecLike.scala:1794)
  at org.scalatest.flatspec.AnyFlatSpec.run(AnyFlatSpec.scala:1685)
  at org.scalatest.Suite.callExecuteOnSuite$1(Suite.scala:1175)
  at org.scalatest.Suite.$anonfun$runNestedSuites$1(Suite.scala:1222)
  at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
  at org.scalatest.Suite.runNestedSuites(Suite.scala:1220)
  at org.scalatest.Suite.runNestedSuites$(Suite.scala:1154)
  at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:30)
  at org.scalatest.Suite.run(Suite.scala:1109)
  at org.scalatest.Suite.run$(Suite.scala:1094)
  at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:30)
  at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
  at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1322)
  at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1316)
  at scala.collection.immutable.List.foreach(List.scala:333)
  at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1316)
  at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:993)
  at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:971)
  at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1482)
  at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
  at org.scalatest.tools.Runner$.main(Runner.scala:775)
  at org.scalatest.tools.Runner.main(Runner.scala)
  at io.bazel.rulesscala.scala_test.Runner.main(Runner.java:34)
  Cause: java.util.NoSuchElementException: None.get
  at scala.None$.get(Option.scala:627)
  at scala.None$.get(Option.scala:626)
  at org.scalatest.OptionValues$Valuable.value(OptionValues.scala:110)
  at com.daml.ledger.rxjava.grpc.CommandSubmissionClientImplTest.$anonfun$new$3(CommandSubmissionClientImplTest.scala:59)
  at org.scalatest.Assertions.withClue(Assertions.scala:1065)
  at org.scalatest.Assertions.withClue$(Assertions.scala:1052)
  at org.scalatest.flatspec.AnyFlatSpec.withClue(AnyFlatSpec.scala:1685)
  at com.daml.ledger.rxjava.grpc.CommandSubmissionClientImplTest.$anonfun$new$2(CommandSubmissionClientImplTest.scala:46)
  at com.daml.ledger.rxjava.grpc.helpers.LedgerServices.$anonfun$withCommandSubmissionClient$1(LedgerServices.scala:131)
  at com.daml.ledger.rxjava.grpc.helpers.LedgerServices.$anonfun$withServerAndChannel$1(LedgerServices.scala:75)
  at com.daml.ledger.rxjava.grpc.helpers.LedgerServices.withServer(LedgerServices.scala:59)
  at com.daml.ledger.rxjava.grpc.helpers.LedgerServices.withServerAndChannel(LedgerServices.scala:70)
  at com.daml.ledger.rxjava.grpc.helpers.LedgerServices.withCommandSubmissionClient(LedgerServices.scala:130)
  at com.daml.ledger.rxjava.grpc.CommandSubmissionClientImplTest.$anonfun$new$1(CommandSubmissionClientImplTest.scala:43)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.flatspec.AnyFlatSpecLike$$anon$5.apply(AnyFlatSpecLike.scala:1683)
  at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
  at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
  at org.scalatest.flatspec.AnyFlatSpec.withFixture(AnyFlatSpec.scala:1685)
  at org.scalatest.flatspec.AnyFlatSpecLike.invokeWithFixture$1(AnyFlatSpecLike.scala:1681)
  at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTest$1(AnyFlatSpecLike.scala:1693)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
  at org.scalatest.flatspec.AnyFlatSpecLike.runTest(AnyFlatSpecLike.scala:1693)
  at org.scalatest.flatspec.AnyFlatSpecLike.runTest$(AnyFlatSpecLike.scala:1675)
  at org.scalatest.flatspec.AnyFlatSpec.runTest(AnyFlatSpec.scala:1685)
  at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTests$1(AnyFlatSpecLike.scala:1751)
  at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
  at scala.collection.immutable.List.foreach(List.scala:333)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
  at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
  at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
  at scala.collection.immutable.List.foreach(List.scala:333)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
  at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
  at org.scalatest.flatspec.AnyFlatSpecLike.runTests(AnyFlatSpecLike.scala:1751)
  at org.scalatest.flatspec.AnyFlatSpecLike.runTests$(AnyFlatSpecLike.scala:1750)
  at org.scalatest.flatspec.AnyFlatSpec.runTests(AnyFlatSpec.scala:1685)
  at org.scalatest.Suite.run(Suite.scala:1112)
  at org.scalatest.Suite.run$(Suite.scala:1094)
  at org.scalatest.flatspec.AnyFlatSpec.org$scalatest$flatspec$AnyFlatSpecLike$$super$run(AnyFlatSpec.scala:1685)
  at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$run$1(AnyFlatSpecLike.scala:1796)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
  at org.scalatest.flatspec.AnyFlatSpecLike.run(AnyFlatSpecLike.scala:1796)
  at org.scalatest.flatspec.AnyFlatSpecLike.run$(AnyFlatSpecLike.scala:1794)
  at org.scalatest.flatspec.AnyFlatSpec.run(AnyFlatSpec.scala:1685)
  at org.scalatest.Suite.callExecuteOnSuite$1(Suite.scala:1175)
  at org.scalatest.Suite.$anonfun$runNestedSuites$1(Suite.scala:1222)
  at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
  at org.scalatest.Suite.runNestedSuites(Suite.scala:1220)
  at org.scalatest.Suite.runNestedSuites$(Suite.scala:1154)
  at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:30)
  at org.scalatest.Suite.run(Suite.scala:1109)
  at org.scalatest.Suite.run$(Suite.scala:1094)
  at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:30)
  at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
  at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1322)
  at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1316)
  at scala.collection.immutable.List.foreach(List.scala:333)
  at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1316)
  at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:993)
  at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:971)
  at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1482)
  at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
  at org.scalatest.tools.Runner$.main(Runner.scala:775)
  at org.scalatest.tools.Runner.main(Runner.scala)
  at io.bazel.rulesscala.scala_test.Runner.main(Runner.java:34)
- should send a commands to the ledger (170 milliseconds)
Authorization
- should fail without a token (110 milliseconds)
- should fail with the wrong token (69 milliseconds)
- should fail with insufficient authorization (43 milliseconds)
- should succeed with the correct authorization (36 milliseconds)
Run completed in 3 seconds, 636 milliseconds.
Total number of tests run: 6
Suites: completed 2, aborted 0
Tests: succeeded 5, failed 1, canceled 0, ignored 0, pending 0
*** 1 TEST FAILED ***
================================================================================
```

**Comment by stefanobaghino-da** [comment]
The following is the failing test

```scala
  it should "timeout should work as expected across calls" in {
    ledgerServices.withCommandSubmissionClient(
      sequence(stuck, success, stuck),
      timeout = Optional.of(Duration.of(1, ChronoUnit.SECONDS)),
    ) { (client, serviceImpl) =>
      val commands = genCommands(List.empty)

      withClue("The first command should be stuck") {
        expectDeadlineExceeded(
          client
            .submit(
              commands.getWorkflowId,
              commands.getApplicationId,
              commands.getCommandId,
              commands.getParty,
              commands.getCommands,
            )
            .timeout(TestConfiguration.timeoutInSeconds, TimeUnit.SECONDS)
            .blockingGet()
        )
        // FAILS AT THE FOLLOWING LINE
        serviceImpl.getSubmittedRequest.value.getCommands.ledgerId shouldBe ledgerServices.ledgerId
      }

      withClue("The second command should go through") {
        client
          .submit(
            commands.getWorkflowId,
            commands.getApplicationId,
            commands.getCommandId,
            commands.getParty,
            commands.getCommands,
          )
          .timeout(TestConfiguration.timeoutInSeconds, TimeUnit.SECONDS)
          .blockingGet()
        serviceImpl.getSubmittedRequest.value.getCommands.ledgerId shouldBe ledgerServices.ledgerId
      }

      withClue("The third command should be stuck") {
        expectDeadlineExceeded(
          client
            .submit(
              commands.getWorkflowId,
              commands.getApplicationId,
              commands.getCommandId,
              commands.getParty,
              commands.getCommands,
            )
            .timeout(TestConfiguration.timeoutInSeconds, TimeUnit.SECONDS)
            .blockingGet()
        )
        serviceImpl.getSubmittedRequest.value.getCommands.ledgerId shouldBe ledgerServices.ledgerId
      }
    }
  }
```

where `serviceImpl` is a mock defined in `com.daml.ledger.rxjava.grpc.helpers.CommandSubmissionServiceImpl` that saves the submitted request for inspection later on. In principle the failing calls can be removed because what the test really cares about is:
* does the client throw a `DEADLINE_EXCEEDED` if the call hits the timeout because of a slow response from the service?
* does the timeout work as expected in subsequent calls?
The latter point is required to address the concern raised [here](https://github.com/digital-asset/daml/pull/10384#issuecomment-907529728) (this is a comment on a PR that was somewhat confusingly used to track an issue).

My first attempt removing the `getSubmittedRequest` calls cause the test to still fail unexpectedly on the second call because the timeout is hit (despite the second mock response being an immediate success). I'm not 100% of why this is.

The test fails pretty consistently as soon as you have multiple tests running at the same time, e.g. with the following:

```
bazel test --runs_per_test=8 //language-support/java/bindings-rxjava:bindings-java-tests_test_suite_src_test_scala_com_daml_ledger_rxjava_grpc_CommandSubmissionClientImplTest.scala
```

I have not been able to pinpoint the cause precisely, but given what I've seen so far I suspect that the fact that the test uses the global execution context could be the source of the issue (see `com.daml.ledger.rxjava.grpc.helpers.LedgerServices`).
