### ISSUE TITLE
Flake in //language-support/java/bindings-rxjava:bindings-java-tests_test_suite_src_test_scala_com_daml_ledger_rxjava_grpc_PackageClientImplTest.scala

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#10974]
Only seen it once so far
```
2021-09-22T06:55:34.8280150Z ==================== Test output for //language-support/java/bindings-rxjava:bindings-java-tests_test_suite_src_test_scala_com_daml_ledger_rxjava_grpc_PackageClientImplTest.scala:
2021-09-22T06:55:34.8289040Z Discovery starting.
2021-09-22T06:55:34.8294470Z Discovery completed in 1 second, 2 milliseconds.
2021-09-22T06:55:34.8325500Z Run starting. Expected test count is: 9
2021-09-22T06:55:34.8330590Z PackageClientImplTest:
2021-09-22T06:55:34.8331820Z [7.1] PackageClientImpl.listPackages
2021-09-22T06:55:34.8347930Z - should return the packages from the Ledger (2 seconds, 147 milliseconds)
2021-09-22T06:55:34.8349390Z [7.2] PackageClientImpl.listPackages
2021-09-22T06:55:34.8351190Z - should request the list of packages with the correct ledger ID (84 milliseconds)
2021-09-22T06:55:34.8352180Z [7.3] PackageClientImpl.getPackage
2021-09-22T06:55:34.8415660Z - should return the package from the Ledger (190 milliseconds)
2021-09-22T06:55:34.8417380Z [7.4] PackageClientImpl.getPackage
2021-09-22T06:55:34.8421210Z - should request the package with the correct ledger ID and package ID (79 milliseconds)
2021-09-22T06:55:34.8422560Z [7.5] PackageClientImpl.getPackageStatus
2021-09-22T06:55:34.8424190Z - should return the packageStatus from the Ledger (65 milliseconds)
2021-09-22T06:55:34.8427150Z [7.6] PackageClientImpl.getPackageStatus
2021-09-22T06:55:34.8429410Z - should send a request with the correct ledger ID and packageID (45 milliseconds)
2021-09-22T06:55:34.8430570Z Authorization
2021-09-22T06:55:34.8434400Z - should deny access without token (217 milliseconds)
2021-09-22T06:55:34.8457640Z - should deny access without sufficient authorization *** FAILED *** (208 milliseconds)
2021-09-22T06:55:34.8459630Z   getPackageStatus <iterator> was empty (AuthMatchers.scala:16)
2021-09-22T06:55:34.8460900Z   org.scalatest.exceptions.TestFailedException:
2021-09-22T06:55:34.8463320Z   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:402)
2021-09-22T06:55:34.8465850Z   at org.scalatest.matchers.dsl.ResultOfNotWordForAny.be(ResultOfNotWordForAny.scala:670)
2021-09-22T06:55:34.8467680Z   at com.daml.ledger.rxjava.AuthMatchers.expectError(AuthMatchers.scala:16)
2021-09-22T06:55:34.8469190Z   at com.daml.ledger.rxjava.AuthMatchers.expectUnauthenticated(AuthMatchers.scala:22)
2021-09-22T06:55:34.8470640Z   at com.daml.ledger.rxjava.AuthMatchers.expectUnauthenticated$(AuthMatchers.scala:18)
2021-09-22T06:55:34.8472240Z   at com.daml.ledger.rxjava.grpc.PackageClientImplTest.expectUnauthenticated(PackageClientImplTest.scala:18)
2021-09-22T06:55:34.8473870Z   at com.daml.ledger.rxjava.grpc.PackageClientImplTest.$anonfun$new$27(PackageClientImplTest.scala:166)
2021-09-22T06:55:34.8475290Z   at org.scalatest.Assertions.withClue(Assertions.scala:1065)
2021-09-22T06:55:34.8476390Z   at org.scalatest.Assertions.withClue$(Assertions.scala:1052)
2021-09-22T06:55:34.8477510Z   at org.scalatest.flatspec.AnyFlatSpec.withClue(AnyFlatSpec.scala:1685)
2021-09-22T06:55:34.8478880Z   at com.daml.ledger.rxjava.grpc.PackageClientImplTest.$anonfun$new$23(PackageClientImplTest.scala:165)
2021-09-22T06:55:34.8480380Z   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
2021-09-22T06:55:34.8481580Z   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
2021-09-22T06:55:34.8482810Z   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
2021-09-22T06:55:34.8485450Z   at org.scalatest.Transformer.apply(Transformer.scala:22)
2021-09-22T06:55:34.8487130Z   at org.scalatest.Transformer.apply(Transformer.scala:20)
2021-09-22T06:55:34.8488640Z   at org.scalatest.flatspec.AnyFlatSpecLike$$anon$5.apply(AnyFlatSpecLike.scala:1683)
2021-09-22T06:55:34.8490520Z   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
2021-09-22T06:55:34.8491750Z   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
2021-09-22T06:55:34.8493020Z   at org.scalatest.flatspec.AnyFlatSpec.withFixture(AnyFlatSpec.scala:1685)
2021-09-22T06:55:34.8494330Z   at org.scalatest.flatspec.AnyFlatSpecLike.invokeWithFixture$1(AnyFlatSpecLike.scala:1681)
2021-09-22T06:55:34.8495630Z   at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTest$1(AnyFlatSpecLike.scala:1693)
2021-09-22T06:55:34.8496690Z   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
2021-09-22T06:55:34.8497860Z   at org.scalatest.flatspec.AnyFlatSpecLike.runTest(AnyFlatSpecLike.scala:1693)
2021-09-22T06:55:34.8499190Z   at org.scalatest.flatspec.AnyFlatSpecLike.runTest$(AnyFlatSpecLike.scala:1675)
2021-09-22T06:55:34.8500480Z   at org.scalatest.flatspec.AnyFlatSpec.runTest(AnyFlatSpec.scala:1685)
2021-09-22T06:55:34.8501820Z   at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTests$1(AnyFlatSpecLike.scala:1751)
2021-09-22T06:55:34.8503110Z   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
2021-09-22T06:55:34.8504340Z   at scala.collection.immutable.List.foreach(List.scala:333)
2021-09-22T06:55:34.8505530Z   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
2021-09-22T06:55:34.8506750Z   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
2021-09-22T06:55:34.8509840Z   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
2021-09-22T06:55:34.8510930Z   at scala.collection.immutable.List.foreach(List.scala:333)
2021-09-22T06:55:34.8512080Z   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
2021-09-22T06:55:34.8513320Z   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
2021-09-22T06:55:34.8514530Z   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
2021-09-22T06:55:34.8515800Z   at org.scalatest.flatspec.AnyFlatSpecLike.runTests(AnyFlatSpecLike.scala:1751)
2021-09-22T06:55:34.8517200Z   at org.scalatest.flatspec.AnyFlatSpecLike.runTests$(AnyFlatSpecLike.scala:1750)
2021-09-22T06:55:34.8518530Z   at org.scalatest.flatspec.AnyFlatSpec.runTests(AnyFlatSpec.scala:1685)
2021-09-22T06:55:34.8519710Z   at org.scalatest.Suite.run(Suite.scala:1112)
2021-09-22T06:55:34.8520750Z   at org.scalatest.Suite.run$(Suite.scala:1094)
2021-09-22T06:55:34.8524250Z   at org.scalatest.flatspec.AnyFlatSpec.org$scalatest$flatspec$AnyFlatSpecLike$$super$run(AnyFlatSpec.scala:1685)
2021-09-22T06:55:34.8525990Z   at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$run$1(AnyFlatSpecLike.scala:1796)
2021-09-22T06:55:34.8527600Z   at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
2021-09-22T06:55:34.8528990Z   at org.scalatest.flatspec.AnyFlatSpecLike.run(AnyFlatSpecLike.scala:1796)
2021-09-22T06:55:34.8530280Z   at org.scalatest.flatspec.AnyFlatSpecLike.run$(AnyFlatSpecLike.scala:1794)
2021-09-22T06:55:34.8531580Z   at org.scalatest.flatspec.AnyFlatSpec.run(AnyFlatSpec.scala:1685)
2021-09-22T06:55:34.8532770Z   at org.scalatest.Suite.callExecuteOnSuite$1(Suite.scala:1175)
2021-09-22T06:55:34.8535660Z   at org.scalatest.Suite.$anonfun$runNestedSuites$1(Suite.scala:1222)
2021-09-22T06:55:34.8537110Z   at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
2021-09-22T06:55:34.8538320Z   at org.scalatest.Suite.runNestedSuites(Suite.scala:1220)
2021-09-22T06:55:34.8539530Z   at org.scalatest.Suite.runNestedSuites$(Suite.scala:1154)
2021-09-22T06:55:34.8540670Z   at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:30)
2021-09-22T06:55:34.8541840Z   at org.scalatest.Suite.run(Suite.scala:1109)
2021-09-22T06:55:34.8542850Z   at org.scalatest.Suite.run$(Suite.scala:1094)
2021-09-22T06:55:34.8544650Z   at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:30)
2021-09-22T06:55:34.8545680Z   at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
2021-09-22T06:55:34.8546470Z   at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1322)
2021-09-22T06:55:34.8548070Z   at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1316)
2021-09-22T06:55:34.8549580Z   at scala.collection.immutable.List.foreach(List.scala:333)
2021-09-22T06:55:34.8550570Z   at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1316)
2021-09-22T06:55:34.8551420Z   at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:993)
2021-09-22T06:55:34.8552300Z   at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:971)
2021-09-22T06:55:34.8553170Z   at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1482)
2021-09-22T06:55:34.8553980Z   at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
2021-09-22T06:55:34.8557900Z   at org.scalatest.tools.Runner$.main(Runner.scala:775)
2021-09-22T06:55:34.8560000Z   at org.scalatest.tools.Runner.main(Runner.scala)
2021-09-22T06:55:34.8563280Z   at io.bazel.rulesscala.scala_test.Runner.main(Runner.java:34)
2021-09-22T06:55:34.8566320Z - should allow access with sufficient authorization (124 milliseconds)
2021-09-22T06:55:34.8570590Z Run completed in 4 seconds, 411 milliseconds.
2021-09-22T06:55:34.8571740Z Total number of tests run: 9
2021-09-22T06:55:34.8572640Z Suites: completed 2, aborted 0
2021-09-22T06:55:34.8575710Z Tests: succeeded 8, failed 1, canceled 0, ignored 0, pending 0
2021-09-22T06:55:34.8576950Z *** 1 TEST FAILED ***
```

**Comment by stefanobaghino-da** [comment]
On what build did this fail? I ran it a few hundred times on my Linux laptop and it never failed.

**Comment by cocreature** [comment]
Today’s snapshot release build on macos

**Comment by stefanobaghino-da** [comment]
Not a fix but https://github.com/digital-asset/daml/issues/10981 should help at identifying the issue a bit better next time this happens.

**Comment by mziolekda** [comment]
Closing, obsolete issue
