### ISSUE TITLE
[BUG] Cannot use Daml Script's allocateParty against the HTTP JSON API

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#11201]
I confirm that, if this is a bug that has security implications, I already contacted security@digitalasset.com and followed the [responsible disclosure policy](https://digitalasset.com/security/).

I confirm that this is not a question or a request for technical support by the community, for which the [Daml forum](https://discuss.daml.com/) is available.

**Affected Daml version**
1.0.0

**Bug description**
If `allocateParty` (without a hint) is invoked from Daml Script when running against the HTTP JSON API (`--json-api`), the following error is thrown:

```
Exception in thread "main" java.lang.RuntimeException: Failed to allocate party: HttpResponse(400 Bad Request,List(Server: akka-http/10.1.11, Date: Mon, 11 Oct 2021 16:47:03 GMT),HttpEntity.Strict(application/json,71 bytes total),HttpProtocol(HTTP/1.1)), {"errors":["PartiesService.toLedgerApi \"empty string\""],"status":400}
	at com.daml.lf.engine.script.JsonLedgerClient.$anonfun$allocateParty$3(LedgerInteraction.scala:347)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:47)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:47)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

**To reproduce**
1. start the sandbox and HTTP JSON API
2. write a Daml Script that attempts to use `allocateParty` without a hint
3. run the Daml Script against the HTTP JSON API

**Expected behavior**
The command succeeds and the party is successfully allocated.

**Comment by mziolekda** [comment]
Closing, obsolete issue
