### ISSUE TITLE
flake in //ledger-service/http-json:integration-tests-ee

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#11585]
We’ve seen timeouts in `archiving a large number of contracts should succeed` and now also

```
[31m- fetch should receive deltas as contracts are archived/created, filtering out phantom archives *** FAILED *** (6 seconds, 888 milliseconds)[0m
[31m  akka.http.scaladsl.model.ws.PeerClosedConnectionException: Peer closed connection with code 1011 'internal error'[0m
[31m  at akka.http.impl.engine.ws.WebSocket$PrepareForUserHandler$$anon$1.onPush(WebSocket.scala:115)[0m
[31m  at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)[0m
[31m  at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:495)[0m
[31m  at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)[0m
[31m  at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)[0m
[31m  at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:502)[0m
[31m  at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)[0m
[31m  at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:773)[0m
[31m  at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:788)[0m
[31m  at akka.actor.Actor.aroundReceive(Actor.scala:537)[0m
[31m  at akka.actor.Actor.aroundReceive$(Actor.scala:535)[0m
[31m  at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)[0m
[31m  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)[0m
[31m  at akka.actor.ActorCell.invoke(ActorCell.scala:547)[0m
[31m  at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)[0m
[31m  at akka.dispatch.Mailbox.run(Mailbox.scala:231)[0m
[31m  at akka.dispatch.Mailbox.exec(Mailbox.scala:243)[0m
[31m  at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)[0m
[31m  at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)[0m
[31m  at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)[0m
[31m  at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)[0m
```

**Comment by stefanobaghino-da** [comment]
Is there a link to the failed build? The logs would tell much more than the stacktrace.

**Comment by cocreature** [comment]
don’t have one handy atm

**Comment by mziolekda** [comment]
Closing, obsolete issue
