### ISSUE TITLE
Trigger service tests are flaky

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#11753]
```
2021-11-17T18:26:42.0572081Z - should should enable a trigger on http request *** FAILED *** (6 seconds, 318 milliseconds)
2021-11-17T18:26:42.0572844Z   com.daml.timer.RetryStrategy$TooManyAttemptsException: Gave up trying after 5 attempts and 4.513001663 seconds.
2021-11-17T18:26:42.0573759Z   at com.daml.timer.RetryStrategy$$anonfun$com$daml$timer$RetryStrategy$$go$1$1.applyOrElse(RetryStrategy.scala:92)
2021-11-17T18:26:42.0574638Z   at com.daml.timer.RetryStrategy$$anonfun$com$daml$timer$RetryStrategy$$go$1$1.applyOrElse(RetryStrategy.scala:89)
2021-11-17T18:26:42.0575404Z   at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:454)
2021-11-17T18:26:42.0576101Z   at org.scalatest.concurrent.SerialExecutionContext.recRunNow(SerialExecutionContext.scala:120)
2021-11-17T18:26:42.0576848Z   at org.scalatest.concurrent.SerialExecutionContext.runNow(SerialExecutionContext.scala:111)
2021-11-17T18:26:42.0577585Z   at org.scalatest.AsyncSuperEngine.runTestImpl(AsyncEngine.scala:377)
2021-11-17T18:26:42.0578212Z   at org.scalatest.flatspec.AsyncFlatSpecLike.runTest(AsyncFlatSpecLike.scala:1839)
2021-11-17T18:26:42.0579074Z   at org.scalatest.flatspec.AsyncFlatSpecLike.runTest$(AsyncFlatSpecLike.scala:1818)
2021-11-17T18:26:42.0579940Z   at com.daml.lf.engine.trigger.TriggerServiceTestAuth.org$scalatest$BeforeAndAfterEach$$super$runTest(TriggerServiceTestAuth.scala:6)
```
[test.log](https://github.com/digital-asset/daml/files/7557682/test.log)

Seen this a few times now I think

**Comment by mziolekda** [comment]
Closing, obsolete issue
