### ISSUE TITLE
Flake candidate in `LedgerClientAuthIT`

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#12886]
```
2022-02-11T09:27:44.3018510Z ==================== Test output for //ledger/ledger-api-client:ledger-api-client-integration-tests_test_suite_src_it_scala_com_digitalasset_ledger_client_LedgerClientAuthIT.scala:
2022-02-11T09:27:44.3020630Z Discovery starting.
2022-02-11T09:27:44.3021890Z Discovery completed in 1 second, 209 milliseconds.
2022-02-11T09:27:44.3023220Z Run starting. Expected test count is: 4
2022-02-11T09:27:44.3024300Z LedgerClientAuthIT:
2022-02-11T09:27:44.3025210Z the ledger client
2022-02-11T09:27:44.3027230Z   when it has a read-only token
2022-02-11T09:27:44.3028420Z    ____             ____
2022-02-11T09:27:44.3029440Z   / __/__ ____  ___/ / /  ___ __ __
2022-02-11T09:27:44.3030450Z  _\ \/ _ `/ _ \/ _  / _ \/ _ \\ \ /
2022-02-11T09:27:44.3031830Z /___/\_,_/_//_/\_,_/_.__/\___/_\_\
2022-02-11T09:27:44.3032580Z 
2022-02-11T09:27:44.3035360Z   - should retrieve the ledger ID (822 milliseconds)
2022-02-11T09:27:44.3038780Z [INFO] [02/11/2022 09:27:39.617] [LedgerClientAuthIT-thread-pool-worker-3] [CoordinatedShutdown(akka://sandbox)] Running CoordinatedShutdown with reason [ActorSystemTerminateReason]
2022-02-11T09:27:44.3042700Z [INFO] [02/11/2022 09:27:40.571] [LedgerClientAuthIT-thread-pool-worker-6] [CoordinatedShutdown(akka://sandbox)] Running CoordinatedShutdown with reason [ActorSystemTerminateReason]
2022-02-11T09:27:44.3044790Z    ____             ____
2022-02-11T09:27:44.3045730Z   / __/__ ____  ___/ / /  ___ __ __
2022-02-11T09:27:44.3046860Z  _\ \/ _ `/ _ \/ _  / _ \/ _ \\ \ /
2022-02-11T09:27:44.3048970Z /___/\_,_/_//_/\_,_/_.__/\___/_\_\
2022-02-11T09:27:44.3049580Z 
2022-02-11T09:27:44.3052270Z   - should succeed in conducting an admin operation with an admin token (354 milliseconds)
2022-02-11T09:27:44.3055880Z [INFO] [02/11/2022 09:27:41.699] [LedgerClientAuthIT-thread-pool-worker-4] [CoordinatedShutdown(akka://sandbox)] Running CoordinatedShutdown with reason [ActorSystemTerminateReason]
2022-02-11T09:27:44.3057930Z   when it does not have a token
2022-02-11T09:27:44.3058940Z    ____             ____
2022-02-11T09:27:44.3059960Z   / __/__ ____  ___/ / /  ___ __ __
2022-02-11T09:27:44.3060930Z  _\ \/ _ `/ _ \/ _  / _ \/ _ \\ \ /
2022-02-11T09:27:44.3061900Z /___/\_,_/_//_/\_,_/_.__/\___/_\_\
2022-02-11T09:27:44.3062390Z 
2022-02-11T09:27:44.3064100Z   - should fail to construct (129 milliseconds)
2022-02-11T09:27:44.3066950Z [INFO] [02/11/2022 09:27:42.688] [LedgerClientAuthIT-thread-pool-worker-13] [CoordinatedShutdown(akka://sandbox)] Running CoordinatedShutdown with reason [ActorSystemTerminateReason]
2022-02-11T09:27:44.3070130Z ScalaTest can't report this exception because another preceded it, so printing its stack trace:
2022-02-11T09:27:44.3072020Z java.lang.NullPointerException
2022-02-11T09:27:44.3073560Z 	at scala.io.Source$.fromResource(Source.scala:181)
2022-02-11T09:27:44.3075130Z 	at com.daml.platform.sandbox.banner.Banner$.show(Banner.scala:16)
2022-02-11T09:27:44.3077470Z 	at com.daml.ledger.sandbox.SandboxServer.initializationLoggingHeader(SandboxServer.scala:80)
2022-02-11T09:27:44.3079440Z 	at com.daml.ledger.sandbox.SandboxServer.$anonfun$acquire$9(SandboxServer.scala:72)
2022-02-11T09:27:44.3081320Z 	at com.daml.ledger.sandbox.SandboxServer.$anonfun$acquire$9$adapted(SandboxServer.scala:70)
2022-02-11T09:27:44.3083110Z 	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
2022-02-11T09:27:44.3084850Z 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
2022-02-11T09:27:44.3086790Z 	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
2022-02-11T09:27:44.3088630Z 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
2022-02-11T09:27:44.3090290Z 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
2022-02-11T09:27:44.3092410Z 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
2022-02-11T09:27:44.3094520Z 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
2022-02-11T09:27:44.3096240Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-02-11T09:27:44.3098120Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-02-11T09:27:44.3099850Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2022-02-11T09:27:44.3103480Z [INFO] [02/11/2022 09:27:42.731] [ScalaTest-main-running-DiscoverySuite] [CoordinatedShutdown(akka://LedgerClientAuthIT)] Running CoordinatedShutdown with reason [ActorSystemTerminateReason]
2022-02-11T09:27:44.3105860Z com.daml.ledger.client.LedgerClientAuthIT *** ABORTED *** (13 seconds, 985 milliseconds)
2022-02-11T09:27:44.3107670Z   org.scalactic.exceptions.NullArgumentException: SuiteAborted.this.message was null
2022-02-11T09:27:44.3109580Z   at org.scalactic.Requirements$RequirementsHelper.macroRequireNonNull(Requirements.scala:517)
2022-02-11T09:27:44.3112450Z   at org.scalatest.events.SuiteAborted.<init>(Event.scala:1178)
2022-02-11T09:27:44.3114340Z   at org.scalatest.Suite.callExecuteOnSuite$1(Suite.scala:1184)
2022-02-11T09:27:44.3116090Z   at org.scalatest.Suite.$anonfun$runNestedSuites$1(Suite.scala:1222)
2022-02-11T09:27:44.3117850Z   at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1328)
2022-02-11T09:27:44.3119560Z   at org.scalatest.Suite.runNestedSuites(Suite.scala:1220)
2022-02-11T09:27:44.3121170Z   at org.scalatest.Suite.runNestedSuites$(Suite.scala:1154)
2022-02-11T09:27:44.3122880Z   at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:30)
2022-02-11T09:27:44.3125330Z   at org.scalatest.Suite.run(Suite.scala:1109)
2022-02-11T09:27:44.3126770Z   at org.scalatest.Suite.run$(Suite.scala:1094)
2022-02-11T09:27:44.3128370Z   at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:30)
2022-02-11T09:27:44.3130030Z   at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
2022-02-11T09:27:44.3132200Z   at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1322)
2022-02-11T09:27:44.3134430Z   at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1316)
2022-02-11T09:27:44.3136280Z   at scala.collection.immutable.List.foreach(List.scala:333)
2022-02-11T09:27:44.3137980Z   at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1316)
2022-02-11T09:27:44.3147670Z   at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:993)
2022-02-11T09:27:44.3160820Z   at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:971)
2022-02-11T09:27:44.3164320Z   at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1482)
2022-02-11T09:27:44.3168670Z   at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
2022-02-11T09:27:44.3176110Z   at org.scalatest.tools.Runner$.main(Runner.scala:775)
2022-02-11T09:27:44.3177750Z   at org.scalatest.tools.Runner.main(Runner.scala)
2022-02-11T09:27:44.3179280Z   at io.bazel.rulesscala.scala_test.Runner.main(Runner.java:33)
2022-02-11T09:27:44.3180790Z Run completed in 15 seconds, 309 milliseconds.
2022-02-11T09:27:44.3182000Z Total number of tests run: 3
2022-02-11T09:27:44.3183120Z Suites: completed 1, aborted 1
2022-02-11T09:27:44.3185760Z Tests: succeeded 3, failed 0, canceled 0, ignored 0, pending 0
2022-02-11T09:27:44.3187060Z *** 1 SUITE ABORTED ***
2022-02-11T09:27:44.3188330Z ================================================================================
```

**Comment by stefanobaghino-da** [comment]
No further reports on this in almost a year, closing.
