### ISSUE TITLE
Flake in create-daml-app tests

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#12941]
Sometimes they seem to fall over with
```
  ● log in as three different users and start following each other

    Protocol error (Runtime.callFunctionOn): Target closed.

      207 |   await usernameInput.type(partyName);
      208 |   await page.click(".test-select-login-button");
    > 209 |   await page.waitForSelector(".test-select-main-menu");
          |              ^
      210 | };
      211 | // LOGIN_FUNCTION_END
      212 |

      at node_modules/puppeteer/lib/Connection.js:156:63
      at CDPSession.send (node_modules/puppeteer/lib/Connection.js:155:16)
      at ExecutionContext._evaluateInternal (node_modules/puppeteer/lib/ExecutionContext.js:85:50)
      at ExecutionContext.evaluateHandle (node_modules/puppeteer/lib/ExecutionContext.js:36:21)
      at ExecutionContext.<anonymous> (node_modules/puppeteer/lib/helper.js:117:27)
      at WaitTask.rerun (node_modules/puppeteer/lib/DOMWorld.js:423:71)
        -- ASYNC --
      at Frame.<anonymous> (node_modules/puppeteer/lib/helper.js:116:19)
      at Page.waitForSelector (node_modules/puppeteer/lib/Page.js:867:33)
      at login (src/index.test.ts:209:14)
      at Object.<anonymous> (src/index.test.ts:279:3)
```

Not quite clear to me what is failing there but I suspect some sychronization/timing issue.

**Comment by cocreature** [comment]
@robin-da can you please take a look at that? I’ve seen it fail a few times on CI now.

**Comment by robin-da** [comment]
This https://github.com/puppeteer/puppeteer/issues/1175 might be related, but so far I fail at recreating the flake locally.

**Comment by robin-da** [comment]
I haven't been able to recreate this. I'll take a look at this again when the flake appears on CI again.

**Comment by cocreature** [comment]
sounds good thanks for investigating

**Comment by cocreature** [comment]
[test.log](https://github.com/digital-asset/daml/files/8203857/test.log)
Got another flake on macos.
