### ISSUE TITLE
Flake in `//language-support/codegen-common:test`

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#13368]
A property-based check failed (hence this is a `flake/confirmed` without going through `flake/candidate` since the cause if most probably not a transient error of some sort).

The `?` could stand for some Unicode codepoint that could not be rendered properly in Azure Pipelines.

```
- should reject empty versions *** FAILED *** (62 milliseconds)
  TestFailedException was thrown during property evaluation.
    Message: Some((?,)) was not equal to None
    Location: (CodegenConfigReaderSpec.scala:35)
    Occurred when passed generated values (
      arg0 = '?',
      arg1 = "?" // 19 shrinks
    )
  org.scalatest.exceptions.GeneratorDrivenPropertyCheckFailedException:
  at org.scalatestplus.scalacheck.CheckerAsserting$$anon$2.indicateFailure(CheckerAsserting.scala:251)
  at org.scalatestplus.scalacheck.CheckerAsserting$$anon$2.indicateFailure(CheckerAsserting.scala:238)
  at org.scalatestplus.scalacheck.UnitCheckerAsserting$CheckerAssertingImpl.check(CheckerAsserting.scala:160)
  at org.scalatestplus.scalacheck.ScalaCheckDrivenPropertyChecks.forAll(ScalaCheckDrivenPropertyChecks.scala:1118)
  at org.scalatestplus.scalacheck.ScalaCheckDrivenPropertyChecks.forAll$(ScalaCheckDrivenPropertyChecks.scala:1086)
  at com.daml.lf.codegen.conf.CodegenConfigReaderSpec.forAll(CodegenConfigReaderSpec.scala:16)
  at com.daml.lf.codegen.conf.CodegenConfigReaderSpec.$anonfun$new$6(CodegenConfigReaderSpec.scala:34)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.flatspec.AnyFlatSpecLike$$anon$5.apply(AnyFlatSpecLike.scala:1683)
  at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
  at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
  at org.scalatest.flatspec.AnyFlatSpec.withFixture(AnyFlatSpec.scala:1685)
  at org.scalatest.flatspec.AnyFlatSpecLike.invokeWithFixture$1(AnyFlatSpecLike.scala:1681)
  at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTest$1(AnyFlatSpecLike.scala:1693)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
  at org.scalatest.flatspec.AnyFlatSpecLike.runTest(AnyFlatSpecLike.scala:1693)
  at org.scalatest.flatspec.AnyFlatSpecLike.runTest$(AnyFlatSpecLike.scala:1675)
  at org.scalatest.flatspec.AnyFlatSpec.runTest(AnyFlatSpec.scala:1685)
  at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTests$1(AnyFlatSpecLike.scala:1751)
  at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
  at scala.collection.immutable.List.foreach(List.scala:333)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
  at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
  at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
  at scala.collection.immutable.List.foreach(List.scala:333)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
  at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
  at org.scalatest.flatspec.AnyFlatSpecLike.runTests(AnyFlatSpecLike.scala:1751)
  at org.scalatest.flatspec.AnyFlatSpecLike.runTests$(AnyFlatSpecLike.scala:1750)
  at org.scalatest.flatspec.AnyFlatSpec.runTests(AnyFlatSpec.scala:1685)
  at org.scalatest.Suite.run(Suite.scala:1112)
  at org.scalatest.Suite.run$(Suite.scala:1094)
  at org.scalatest.flatspec.AnyFlatSpec.org$scalatest$flatspec$AnyFlatSpecLike$$super$run(AnyFlatSpec.scala:1685)
  at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$run$1(AnyFlatSpecLike.scala:1796)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
  at org.scalatest.flatspec.AnyFlatSpecLike.run(AnyFlatSpecLike.scala:1796)
  at org.scalatest.flatspec.AnyFlatSpecLike.run$(AnyFlatSpecLike.scala:1794)
  at org.scalatest.flatspec.AnyFlatSpec.run(AnyFlatSpec.scala:1685)
  at org.scalatest.Suite.callExecuteOnSuite$1(Suite.scala:1175)
  at org.scalatest.Suite.$anonfun$runNestedSuites$1(Suite.scala:1222)
  at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1328)
  at org.scalatest.Suite.runNestedSuites(Suite.scala:1220)
  at org.scalatest.Suite.runNestedSuites$(Suite.scala:1154)
  at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:30)
  at org.scalatest.Suite.run(Suite.scala:1109)
  at org.scalatest.Suite.run$(Suite.scala:1094)
  at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:30)
  at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
  at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1322)
  at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1316)
  at scala.collection.immutable.List.foreach(List.scala:333)
  at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1316)
  at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:993)
  at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:971)
  at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1482)
  at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
  at org.scalatest.tools.Runner$.main(Runner.scala:775)
  at org.scalatest.tools.Runner.main(Runner.scala)
  at io.bazel.rulesscala.scala_test.Runner.main(Runner.java:33)
  Cause: org.scalatest.exceptions.TestFailedException: Some((?,)) was not equal to None
  at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
  at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6982)
  at com.daml.lf.codegen.conf.CodegenConfigReaderSpec.$anonfun$new$7(CodegenConfigReaderSpec.scala:35)
  at com.daml.lf.codegen.conf.CodegenConfigReaderSpec.$anonfun$new$7$adapted(CodegenConfigReaderSpec.scala:34)
  at org.scalatestplus.scalacheck.ScalaCheckDrivenPropertyChecks.liftedTree11$1(ScalaCheckDrivenPropertyChecks.scala:1098)
  at org.scalatestplus.scalacheck.ScalaCheckDrivenPropertyChecks.$anonfun$forAll$13(ScalaCheckDrivenPropertyChecks.scala:1097)
  at org.scalacheck.Prop$.$anonfun$forAll$18(Prop.scala:928)
  at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
  at org.scalacheck.Prop$.$anonfun$forAllShrink$2(Prop.scala:768)
  at org.scalacheck.Prop$.secure(Prop.scala:478)
  at org.scalacheck.Prop$.result$1(Prop.scala:768)
  at org.scalacheck.Prop$.$anonfun$forAllShrink$4(Prop.scala:777)
  at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:173)
  at scala.collection.immutable.Stream$Cons.tail(Stream.scala:403)
  at scala.collection.immutable.Stream$Cons.tail(Stream.scala:394)
  at scala.collection.LinearSeqIterator.$anonfun$next$1(LinearSeq.scala:293)
  at scala.collection.LinearSeqIterator$LazyCell.v$lzycompute(LinearSeq.scala:277)
  at scala.collection.LinearSeqIterator$LazyCell.v(LinearSeq.scala:277)
  at scala.collection.LinearSeqIterator.hasNext(LinearSeq.scala:286)
  at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:649)
  at scala.collection.immutable.Stream$.fromIterator(Stream.scala:468)
  at scala.collection.immutable.Stream$.from(Stream.scala:456)
  at scala.collection.immutable.Stream$.from(Stream.scala:356)
  at scala.collection.IterableFactoryDefaults.fromSpecific(Iterable.scala:936)
  at scala.collection.IterableFactoryDefaults.fromSpecific$(Iterable.scala:936)
  at scala.collection.AbstractIterable.fromSpecific(Iterable.scala:926)
  at scala.collection.AbstractIterable.fromSpecific(Iterable.scala:926)
  at scala.collection.IterableOps.dropWhile(Iterable.scala:469)
  at scala.collection.IterableOps.dropWhile$(Iterable.scala:469)
  at scala.collection.AbstractIterable.dropWhile(Iterable.scala:926)
  at org.scalacheck.Prop$.getFirstFailure$1(Prop.scala:778)
  at org.scalacheck.Prop$.shrinker$1(Prop.scala:787)
  at org.scalacheck.Prop$.$anonfun$forAllShrink$1(Prop.scala:808)
  at org.scalacheck.Prop$.$anonfun$apply$1(Prop.scala:308)
  at org.scalacheck.PropFromFun.apply(Prop.scala:21)
  at org.scalacheck.Prop$.result$1(Prop.scala:769)
  at org.scalacheck.Prop$.$anonfun$forAllShrink$1(Prop.scala:807)
  at org.scalacheck.Prop$.$anonfun$apply$1(Prop.scala:308)
  at org.scalacheck.PropFromFun.apply(Prop.scala:21)
  at org.scalacheck.Test$.workerFun$1(Test.scala:434)
  at org.scalacheck.Test$.$anonfun$check$2(Test.scala:466)
  at org.scalacheck.Test$.$anonfun$check$2$adapted(Test.scala:466)
  at org.scalacheck.Platform$.runWorkers(Platform.scala:40)
  at org.scalacheck.Test$.check(Test.scala:466)
  at org.scalatestplus.scalacheck.UnitCheckerAsserting$CheckerAssertingImpl.check(CheckerAsserting.scala:90)
  at org.scalatestplus.scalacheck.ScalaCheckDrivenPropertyChecks.forAll(ScalaCheckDrivenPropertyChecks.scala:1118)
  at org.scalatestplus.scalacheck.ScalaCheckDrivenPropertyChecks.forAll$(ScalaCheckDrivenPropertyChecks.scala:1086)
  at com.daml.lf.codegen.conf.CodegenConfigReaderSpec.forAll(CodegenConfigReaderSpec.scala:16)
  at com.daml.lf.codegen.conf.CodegenConfigReaderSpec.$anonfun$new$6(CodegenConfigReaderSpec.scala:34)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.flatspec.AnyFlatSpecLike$$anon$5.apply(AnyFlatSpecLike.scala:1683)
  at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
  at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
  at org.scalatest.flatspec.AnyFlatSpec.withFixture(AnyFlatSpec.scala:1685)
  at org.scalatest.flatspec.AnyFlatSpecLike.invokeWithFixture$1(AnyFlatSpecLike.scala:1681)
  at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTest$1(AnyFlatSpecLike.scala:1693)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
  at org.scalatest.flatspec.AnyFlatSpecLike.runTest(AnyFlatSpecLike.scala:1693)
  at org.scalatest.flatspec.AnyFlatSpecLike.runTest$(AnyFlatSpecLike.scala:1675)
  at org.scalatest.flatspec.AnyFlatSpec.runTest(AnyFlatSpec.scala:1685)
  at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTests$1(AnyFlatSpecLike.scala:1751)
  at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
  at scala.collection.immutable.List.foreach(List.scala:333)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
  at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
  at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
  at scala.collection.immutable.List.foreach(List.scala:333)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
  at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
  at org.scalatest.flatspec.AnyFlatSpecLike.runTests(AnyFlatSpecLike.scala:1751)
  at org.scalatest.flatspec.AnyFlatSpecLike.runTests$(AnyFlatSpecLike.scala:1750)
  at org.scalatest.flatspec.AnyFlatSpec.runTests(AnyFlatSpec.scala:1685)
  at org.scalatest.Suite.run(Suite.scala:1112)
  at org.scalatest.Suite.run$(Suite.scala:1094)
  at org.scalatest.flatspec.AnyFlatSpec.org$scalatest$flatspec$AnyFlatSpecLike$$super$run(AnyFlatSpec.scala:1685)
  at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$run$1(AnyFlatSpecLike.scala:1796)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
  at org.scalatest.flatspec.AnyFlatSpecLike.run(AnyFlatSpecLike.scala:1796)
  at org.scalatest.flatspec.AnyFlatSpecLike.run$(AnyFlatSpecLike.scala:1794)
  at org.scalatest.flatspec.AnyFlatSpec.run(AnyFlatSpec.scala:1685)
  at org.scalatest.Suite.callExecuteOnSuite$1(Suite.scala:1175)
  at org.scalatest.Suite.$anonfun$runNestedSuites$1(Suite.scala:1222)
  at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1328)
  at org.scalatest.Suite.runNestedSuites(Suite.scala:1220)
  at org.scalatest.Suite.runNestedSuites$(Suite.scala:1154)
  at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:30)
  at org.scalatest.Suite.run(Suite.scala:1109)
  at org.scalatest.Suite.run$(Suite.scala:1094)
  at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:30)
  at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
  at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1322)
  at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1316)
  at scala.collection.immutable.List.foreach(List.scala:333)
  at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1316)
  at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:993)
  at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:971)
  at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1482)
  at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
  at org.scalatest.tools.Runner$.main(Runner.scala:775)
  at org.scalatest.tools.Runner.main(Runner.scala)
```

**Comment by stefanobaghino-da** [comment]
One input that seems to trigger the flake is the `융`.

**Comment by S11001001** [comment]
Example of failing input:

```
separator = '-'
version = "1-2"
```
