### ISSUE TITLE
ledger-api-test-tool sometimes throws GRPC errors

### ISSUE THREAD

**Issue by ghost** [digital-asset/daml#1338]
With the multi-ledger patch applied (https://github.com/digital-asset/daml/pull/1334), which results in more connections, the ledger api test tool throws errors after a while:

```
SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=176, target=localhost:7603} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:103)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:440)
	at com.digitalasset.platform.apitesting.RemoteServerResource.setup(RemoteServerResource.scala:48)
```

This appears to be an issue with GRPC and creating/tearing down many connections: 
https://github.com/googleapis/google-cloud-java/issues/3648

**Comment by stefanobaghino-da** [comment]
No longer a valid ticket, closing.
