### ISSUE TITLE
Flake in //daml-assistant/daml-helper:test-daml-packages

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#13649]
Reported by @nmarton-da .

```
11.9033632Z FAIL: //daml-assistant/daml-helper:test-daml-packages (see /home/vsts/.cache/bazel/_bazel_vsts/704fb9a8c2b8a7269239cfce241f68b9/execroot/com_github_digital_asset_daml/bazel-out/k8-opt/testlogs/daml-assistant/daml-helper/test-daml-packages/test.log)
11.9124265Z INFO: From Testing //daml-assistant/daml-helper:test-daml-packages:
11.9138790Z ==================== Test output for //daml-assistant/daml-helper:test-daml-packages:
11.9144926Z daml packages
11.9146105Z   list
11.9148108Z     succeeds listing packages:                       07:44:19.364 [program-resource-pool-1] INFO  c.d.l.sandbox.AkkaSubmissionsBridge - Instantiated Akka submissions bridge., context: {participantId: "sandbox-participant"}
11.9150801Z 07:44:19.392 [program-resource-pool-2] INFO  c.d.ledger.sandbox.BridgeReadService - Starting Sandbox-on-X read service..., context: {participantId: "sandbox-participant"}
11.9153435Z 07:44:20.154 [sandbox-akka.actor.default-dispatcher-8] INFO  c.d.ledger.sandbox.BridgeReadService - Indexer subscribed to state updates., context: {participantId: "sandbox-participant"}
11.9156237Z 07:44:20.451 [program-resource-pool-2] INFO  c.d.l.sandbox.BridgeWriteService - Write service initialized. Configuration: [submissionBufferSize: 512], context: {participantId: "sandbox-participant"}
11.9158708Z 07:44:21.265 [program-resource-pool-3] INFO  c.d.p.apiserver.LedgerApiServer - Listening on localhost:33529 over plain text., context: {participantId: "sandbox-participant"}
11.9159752Z FAIL (0.28s)
11.9161053Z       daml-assistant/daml-helper/test/DA/Daml/Helper/Test/Packages.hs:32:
11.9313176Z       Missing `test-1.0.0` package in packages list.
11.9315520Z       Use -p '$0=="daml packages.list.succeeds listing packages"' to rerun this test only.
11.9316649Z   list
11.9319566Z     succeeds listing packages against HTTP JSON API: 07:44:21.624 [daml.index.db.threadpool.connection.api-server-3] ERROR c.d.p.s.a.DbDispatcherImpl - INDEX_DB_SQL_NON_TRANSIENT_ERROR(4,0): Processing the request failed due to a non-transient database error: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-210], context: {participantId: "sandbox-participant", queryOffset: 0, metric: "load_configuration_entries", err-context: "{location=DatabaseSelfServiceError.scala:53}"}
11.9324656Z org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-210]
11.9326489Z 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:697)
11.9327689Z 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
11.9328783Z 	at org.h2.message.DbException.get(DbException.java:227)
11.9329747Z 	at org.h2.message.DbException.get(DbException.java:203)
11.9330783Z 	at org.h2.message.DbException.get(DbException.java:192)
11.9331877Z 	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1375)
11.9332918Z 	at org.h2.jdbc.JdbcConnection.setAutoCommit(JdbcConnection.java:402)
11.9333999Z 	at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:388)
11.9335647Z 	at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java)
11.9336932Z 	at com.daml.platform.store.appendonlydao.DataSourceConnectionProvider$$anon$2.runSQL(HikariJdbcConnectionProvider.scala:74)
11.9338269Z 	at com.daml.platform.store.appendonlydao.DbDispatcherImpl.$anonfun$executeSql$2(DbDispatcher.scala:64)
11.9339587Z 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678)
11.9340636Z 	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
11.9341935Z 	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180)
11.9343241Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
11.9344419Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
11.9345428Z 	at java.base/java.lang.Thread.run(Thread.java:829)
11.9347755Z [WARN] [04/20/2022 07:44:21.643] [sandbox-akka.actor.default-dispatcher-7] [RestartWithBackoffSource(akka://sandbox)] Restarting stream due to failure [1]: com.daml.error.definitions.IndexErrors$IndexDbException: INTERNAL: An error occurred. Please contact the operator and inquire about the request <no-correlation-id>
11.9350696Z 07:44:21.802 [daml.index.db.threadpool.connection.api-server-5] ERROR c.d.p.s.a.DbDispatcherImpl - INDEX_DB_SQL_NON_TRANSIENT_ERROR(4,0): Processing the request failed due to a non-transient database error: Table "PARAMETERS" not found (this database is empty); SQL statement:
11.9352101Z 
11.9352765Z       SELECT
11.9353420Z         ledger_end,
11.9354120Z         ledger_end_sequential_id,
11.9355183Z         ledger_end_string_interning_id
11.9356151Z       FROM
11.9356812Z         parameters
11.9358350Z        [42104-210], context: {participantId: "sandbox-participant", metric: "get_ledger_end", err-context: "{location=DatabaseSelfServiceError.scala:53}"}
11.9359673Z org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "PARAMETERS" not found (this database is empty); SQL statement:
11.9360370Z 
11.9360962Z       SELECT
11.9361674Z         ledger_end,
11.9362365Z         ledger_end_sequential_id,
11.9363140Z         ledger_end_string_interning_id
11.9363825Z       FROM
11.9364458Z         parameters
11.9365532Z        [42104-210]
11.9366423Z 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:521)
11.9367529Z 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
11.9368519Z 	at org.h2.message.DbException.get(DbException.java:227)
11.9369496Z 	at org.h2.message.DbException.get(DbException.java:203)
11.9370519Z 	at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8397)
11.9371677Z 	at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8381)
11.9372756Z 	at org.h2.command.Parser.readTableOrView(Parser.java:8370)
11.9373740Z 	at org.h2.command.Parser.readTablePrimary(Parser.java:1866)
11.9374722Z 	at org.h2.command.Parser.readTableReference(Parser.java:2342)
11.9375709Z 	at org.h2.command.Parser.parseSelectFromPart(Parser.java:2793)
11.9376695Z 	at org.h2.command.Parser.parseSelect(Parser.java:2900)
11.9377719Z 	at org.h2.command.Parser.parseQueryPrimary(Parser.java:2783)
11.9378692Z 	at org.h2.command.Parser.parseQueryTerm(Parser.java:2650)
11.9379694Z 	at org.h2.command.Parser.parseQueryExpressionBody(Parser.java:2629)
11.9380799Z 	at org.h2.command.Parser.parseQueryExpressionBodyAndEndOfQuery(Parser.java:2622)
11.9381885Z 	at org.h2.command.Parser.parseQueryExpression(Parser.java:2615)
11.9382840Z 	at org.h2.command.Parser.parseQuery(Parser.java:2576)
11.9383762Z 	at org.h2.command.Parser.parsePrepared(Parser.java:707)
11.9384653Z 	at org.h2.command.Parser.parse(Parser.java:674)
11.9385533Z 	at org.h2.command.Parser.parse(Parser.java:644)
11.9386420Z 	at org.h2.command.Parser.prepareCommand(Parser.java:551)
11.9387404Z 	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:615)
11.9388382Z 	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:553)
11.9389352Z 	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
11.9390561Z 	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
11.9391661Z 	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
11.9392735Z 	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:311)
11.9393765Z 	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
11.9394650Z 	at anorm.SimpleSql.$anonfun$prepareNoGeneratedKeys$1(SimpleSql.scala:55)
11.9395485Z 	at anorm.SimpleSql.unsafeStatement(SimpleSql.scala:79)
11.9396256Z 	at anorm.SimpleSql.unsafeStatement(SimpleSql.scala:68)
11.9397041Z 	at anorm.Sql.$anonfun$preparedStatement$1(Anorm.scala:64)
11.9398026Z 	at resource.DefaultManagedResource.open(AbstractManagedResource.scala:107)
11.9399079Z 	at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:84)
11.9400393Z 	at resource.ManagedResourceOperations$$anon$1.acquireFor(ManagedResourceOperations.scala:47)
11.9401533Z 	at resource.DeferredExtractableManagedResource.acquireFor(AbstractManagedResource.scala:25)
11.9409477Z 	at resource.ManagedResourceOperations.apply(ManagedResourceOperations.scala:31)
11.9410965Z 	at resource.ManagedResourceOperations.apply$(ManagedResourceOperations.scala:31)
11.9412121Z 	at resource.DeferredExtractableManagedResource.apply(AbstractManagedResource.scala:22)
11.9413131Z 	at resource.ManagedResourceOperations.acquireAndGet(ManagedResourceOperations.scala:29)
11.9414131Z 	at resource.ManagedResourceOperations.acquireAndGet$(ManagedResourceOperations.scala:29)
11.9415371Z 	at resource.DeferredExtractableManagedResource.acquireAndGet(AbstractManagedResource.scala:22)
11.9416358Z 	at anorm.Sql$.$anonfun$asTry$1(Anorm.scala:214)
11.9417054Z 	at scala.util.Try$.apply(Try.scala:210)
11.9417743Z 	at anorm.Sql$.asTry(Anorm.scala:214)
11.9418420Z 	at anorm.WithResult.asTry(SqlResult.scala:190)
11.9419139Z 	at anorm.WithResult.asTry$(SqlResult.scala:190)
11.9419856Z 	at anorm.SimpleSql.asTry(SimpleSql.scala:6)
11.9420581Z 	at anorm.WithResult.as(SqlResult.scala:182)
11.9421342Z 	at anorm.WithResult.as$(SqlResult.scala:181)
11.9422060Z 	at anorm.SimpleSql.as(SimpleSql.scala:6)
11.9423046Z 	at com.daml.platform.store.backend.common.ParameterStorageBackendTemplate$.ledgerEnd(ParameterStorageBackendTemplate.scala:53)
11.9424268Z 	at com.daml.platform.store.appendonlydao.JdbcLedgerDao.$anonfun$lookupLedgerEnd$1(JdbcLedgerDao.scala:84)
11.9425479Z 	at com.daml.platform.store.appendonlydao.DataSourceConnectionProvider$$anon$2.$anonfun$runSQL$1(HikariJdbcConnectionProvider.scala:78)
11.9426691Z 	at com.daml.metrics.Timed$.$anonfun$value$1(Timed.scala:18)
11.9427537Z 	at com.codahale.metrics.Timer.time(Timer.java:118)
11.9428294Z 	at com.daml.metrics.Timed$.value(Timed.scala:18)
11.9429265Z 	at com.daml.platform.store.appendonlydao.DataSourceConnectionProvider$$anon$2.runSQL(HikariJdbcConnectionProvider.scala:78)
11.9430699Z 	at com.daml.platform.store.appendonlydao.DbDispatcherImpl.$anonfun$executeSql$2(DbDispatcher.scala:64)
11.9431783Z 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678)
11.9432598Z 	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
11.9433566Z 	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180)
11.9434681Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
11.9436331Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
11.9437359Z 	at java.base/java.lang.Thread.run(Thread.java:829)
```

Remaining log trimmed; [full log here](https://gist.github.com/stephencompall-DA/feccfea832a97ee069b0d0125be14260).

**Comment by mziolekda** [comment]
Closing, obsolete issue
