### ISSUE TITLE
Daml-script: MultiParticipantIT test is falky in windows

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#13737]
Probably due to a synchronization problem that manifest only on windows.

@cocreature said offline 
> it’s been a while since I looked at that code but I suspect we’re synchronizing on the port being up whereas we should be synchroinzing on the port file being written.

**Comment by remyhaemmerle-da** [comment]
Here are the log
```
2022-04-27T20:32:02.6993927Z ==================== Test output for //daml-script/test:test_6:
2022-04-27T20:32:02.6996045Z Discovery starting.
2022-04-27T20:32:02.6996765Z Discovery completed in 1 second, 861 milliseconds.
2022-04-27T20:32:02.6998919Z Run starting. Expected test count is: 3
2022-04-27T20:32:02.6999655Z MultiParticipantIT:
2022-04-27T20:32:02.7000379Z Multi-participant Daml Script
2022-04-27T20:32:02.7001231Z   can multiTest
2022-04-27T20:32:02.7002410Z   - should return 42 *** FAILED *** (3 seconds, 293 milliseconds)
2022-04-27T20:32:02.7004765Z     com.daml.lf.engine.script.ScriptF$FailedCmd: Command allocateParty failed: FAILED_PRECONDITION: PARTY_ALLOCATION_WITHOUT_CONNECTED_DOMAIN(9,bfa40093): Cannot allocate a party without being connected to a domain
2022-04-27T20:32:02.7005783Z Daml stacktrace:
2022-04-27T20:32:02.7006532Z     at com.daml.lf.engine.script.Runner.$anonfun$runWithClients$10(Runner.scala:460)
2022-04-27T20:32:02.7007820Z     at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:475)
2022-04-27T20:32:02.7009224Z     at org.scalatest.concurrent.SerialExecutionContext.recRunNow(SerialExecutionContext.scala:120)
2022-04-27T20:32:02.7010466Z     at org.scalatest.concurrent.SerialExecutionContext.runNow(SerialExecutionContext.scala:111)
2022-04-27T20:32:02.7011870Z     at org.scalatest.AsyncSuperEngine.runTestImpl(AsyncEngine.scala:377)
2022-04-27T20:32:02.7013617Z     at org.scalatest.wordspec.AsyncWordSpecLike.runTest(AsyncWordSpecLike.scala:1224)
2022-04-27T20:32:02.7015160Z     at org.scalatest.wordspec.AsyncWordSpecLike.runTest$(AsyncWordSpecLike.scala:1204)
2022-04-27T20:32:02.7016227Z     at org.scalatest.wordspec.AsyncWordSpec.runTest(AsyncWordSpec.scala:2296)
2022-04-27T20:32:02.7017231Z     at org.scalatest.wordspec.AsyncWordSpecLike.$anonfun$runTests$1(AsyncWordSpecLike.scala:1283)
2022-04-27T20:32:02.7018493Z     at org.scalatest.AsyncSuperEngine.$anonfun$runTestsInBranch$1(AsyncEngine.scala:432)
2022-04-27T20:32:02.7019672Z     at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
2022-04-27T20:32:02.7020442Z     at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
2022-04-27T20:32:02.7021519Z     at scala.collection.immutable.List.foldLeft(List.scala:79)
2022-04-27T20:32:02.7022246Z     at org.scalatest.AsyncSuperEngine.traverseSubNodes$1(AsyncEngine.scala:406)
2022-04-27T20:32:02.7023032Z     at org.scalatest.AsyncSuperEngine.runTestsInBranch(AsyncEngine.scala:479)
2022-04-27T20:32:02.7023795Z     at org.scalatest.AsyncSuperEngine.$anonfun$runTestsInBranch$1(AsyncEngine.scala:460)
2022-04-27T20:32:02.7024640Z     at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
2022-04-27T20:32:02.7025357Z     at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
2022-04-27T20:32:02.7026411Z     at scala.collection.immutable.List.foldLeft(List.scala:79)
2022-04-27T20:32:02.7027921Z     at org.scalatest.AsyncSuperEngine.traverseSubNodes$1(AsyncEngine.scala:406)
2022-04-27T20:32:02.7028981Z     at org.scalatest.AsyncSuperEngine.runTestsInBranch(AsyncEngine.scala:479)
2022-04-27T20:32:02.7029959Z     at org.scalatest.AsyncSuperEngine.$anonfun$runTestsInBranch$1(AsyncEngine.scala:460)
2022-04-27T20:32:02.7030854Z     at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
2022-04-27T20:32:02.7031723Z     at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
2022-04-27T20:32:02.7032568Z     at scala.collection.immutable.List.foldLeft(List.scala:79)
2022-04-27T20:32:02.7033454Z     at org.scalatest.AsyncSuperEngine.traverseSubNodes$1(AsyncEngine.scala:406)
2022-04-27T20:32:02.7034431Z     at org.scalatest.AsyncSuperEngine.runTestsInBranch(AsyncEngine.scala:487)
2022-04-27T20:32:02.7035218Z     at org.scalatest.AsyncSuperEngine.runTestsImpl(AsyncEngine.scala:555)
2022-04-27T20:32:02.7036271Z     at org.scalatest.wordspec.AsyncWordSpecLike.runTests(AsyncWordSpecLike.scala:1283)
2022-04-27T20:32:02.7037318Z     at org.scalatest.wordspec.AsyncWordSpecLike.runTests$(AsyncWordSpecLike.scala:1282)
2022-04-27T20:32:02.7038332Z     at org.scalatest.wordspec.AsyncWordSpec.runTests(AsyncWordSpec.scala:2296)
2022-04-27T20:32:02.7039184Z     at org.scalatest.Suite.run(Suite.scala:1112)
2022-04-27T20:32:02.7040007Z     at org.scalatest.Suite.run$(Suite.scala:1094)
2022-04-27T20:32:02.7041090Z     at org.scalatest.wordspec.AsyncWordSpec.org$scalatest$wordspec$AsyncWordSpecLike$$super$run(AsyncWordSpec.scala:2296)
2022-04-27T20:32:02.7042461Z     at org.scalatest.wordspec.AsyncWordSpecLike.$anonfun$run$1(AsyncWordSpecLike.scala:1328)
2022-04-27T20:32:02.7043525Z     at org.scalatest.AsyncSuperEngine.runImpl(AsyncEngine.scala:625)
2022-04-27T20:32:02.7044298Z     at org.scalatest.wordspec.AsyncWordSpecLike.run(AsyncWordSpecLike.scala:1328)
2022-04-27T20:32:02.7045252Z     at org.scalatest.wordspec.AsyncWordSpecLike.run$(AsyncWordSpecLike.scala:1326)
2022-04-27T20:32:02.7046319Z     at com.daml.lf.engine.script.test.MultiParticipantIT.org$scalatest$BeforeAndAfterAll$$super$run(MultiParticipantIT.scala:17)
2022-04-27T20:32:02.7047433Z     at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
2022-04-27T20:32:02.7048324Z     at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
2022-04-27T20:32:02.7049091Z     at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
2022-04-27T20:32:02.7050019Z     at com.daml.lf.engine.script.test.MultiParticipantIT.run(MultiParticipantIT.scala:17)
2022-04-27T20:32:02.7050825Z     at org.scalatest.Suite.callExecuteOnSuite$1(Suite.scala:1175)
2022-04-27T20:32:02.7051565Z     at org.scalatest.Suite.$anonfun$runNestedSuites$1(Suite.scala:1222)
2022-04-27T20:32:02.7052374Z     at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1328)
2022-04-27T20:32:02.7053160Z     at org.scalatest.Suite.runNestedSuites(Suite.scala:1220)
2022-04-27T20:32:02.7053943Z     at org.scalatest.Suite.runNestedSuites$(Suite.scala:1154)
2022-04-27T20:32:02.7054766Z     at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:30)
2022-04-27T20:32:02.7055592Z     at org.scalatest.Suite.run(Suite.scala:1109)
2022-04-27T20:32:02.7056444Z     at org.scalatest.Suite.run$(Suite.scala:1094)
2022-04-27T20:32:02.7057280Z     at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:30)
2022-04-27T20:32:02.7058059Z     at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
2022-04-27T20:32:02.7058925Z     at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1322)
2022-04-27T20:32:02.7059899Z     at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1316)
2022-04-27T20:32:02.7060821Z     at scala.collection.immutable.List.foreach(List.scala:333)
2022-04-27T20:32:02.7061653Z     at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1316)
2022-04-27T20:32:02.7062615Z     at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:993)
2022-04-27T20:32:02.7063599Z     at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:971)
2022-04-27T20:32:02.7064517Z     at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1482)
2022-04-27T20:32:02.7065495Z     at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
2022-04-27T20:32:02.7066390Z     at org.scalatest.tools.Runner$.main(Runner.scala:775)
2022-04-27T20:32:02.7067253Z     at org.scalatest.tools.Runner.main(Runner.scala)
2022-04-27T20:32:02.7068111Z     at io.bazel.rulesscala.scala_test.Runner.main(Runner.java:33)
2022-04-27T20:32:02.7069228Z     Cause: io.grpc.StatusRuntimeException: FAILED_PRECONDITION: PARTY_ALLOCATION_WITHOUT_CONNECTED_DOMAIN(9,bfa40093): Cannot allocate a party without being connected to a domain
2022-04-27T20:32:02.7070410Z     at io.grpc.Status.asRuntimeException(Status.java:535)
2022-04-27T20:32:02.7071352Z     at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:534)
2022-04-27T20:32:02.7072353Z     at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
2022-04-27T20:32:02.7073132Z     at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
2022-04-27T20:32:02.7074044Z     at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
2022-04-27T20:32:02.7075012Z     at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
2022-04-27T20:32:02.7075653Z     at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
2022-04-27T20:32:02.7076350Z     at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
2022-04-27T20:32:02.7076964Z     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-04-27T20:32:02.7077565Z     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-04-27T20:32:02.7078080Z     at java.base/java.lang.Thread.run(Thread.java:829)
2022-04-27T20:32:02.7078507Z   can partyIdHintTest
2022-04-27T20:32:02.7078896Z   - should respect party id hints (2 seconds, 188 milliseconds)
2022-04-27T20:32:02.7079303Z   can listKnownPartiesTest
2022-04-27T20:32:02.7079702Z   - should list parties on both participants (6 seconds, 233 milliseconds)
2022-04-27T20:32:02.7080340Z [INFO] [04/27/2022 20:31:59.969] [ScalaTest-main-running-DiscoverySuite] [CoordinatedShutdown(akka://MultiParticipantIT)] Running CoordinatedShutdown with reason [ActorSystemTerminateReason]
2022-04-27T20:32:02.7080958Z Run completed in 30 seconds, 530 milliseconds.
2022-04-27T20:32:02.7081304Z Total number of tests run: 3
2022-04-27T20:32:02.7081612Z Suites: completed 2, aborted 0
2022-04-27T20:32:02.7082001Z Tests: succeeded 2, failed 1, canceled 0, ignored 0, pending 0
2022-04-27T20:32:02.7082361Z *** 1 TEST FAILED ***
2022-04-27T20:32:02.7082731Z ================================================================================
```

**Comment by remyhaemmerle-da** [comment]
No apparent flakiness on Linux, but failing more than 33% on windows.
