### ISSUE TITLE
Party allocation when name and hint ar the same.

### ISSUE THREAD

**Issue by leonidr-da** [digital-asset/daml#14466]
# Affected Daml version

2.3.1 (but 2.3.0 too).

# Bug description

Against the Canton sandbox
```
  admin <- allocatePartyWithHint "Admin" $ PartyIdHint "Admin"
```
throws
```
Exception in thread "main" com.daml.lf.engine.script.ScriptF$FailedCmd: Command allocateParty failed: INVALID_ARGUMENT: INVALID_ARGUMENT(8,Admin-87): The submitted command has invalid arguments: Party already exists: party Admin::12201f177236... is already allocated on this node
Daml stacktrace:
allocatePartyWithHint at ae2428c6556e37d7114a8226a6beda53add7338d6918d3da1f2ae3359158350a:Init.AllocateAdmin:10
	at com.daml.lf.engine.script.Runner.$anonfun$runWithClients$10(Runner.scala:466)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:475)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
but
```
  admin <- allocatePartyWithHint "Admin" $ PartyIdHint "Admin_"
```
does not.

# To reproduce

1. Create script that allocates the party.
2. Startup sandbox
3. Execute script

# Expected behavior

Should work.

# Additional context

**Comment by leonidr-da** [comment]
Nevermind ... it seems like this has to do with the state of the sandbox not with party allocation specifically.
