### ISSUE TITLE
GetTransactionById results in "java.util.NoSuchElementException: key not found: 9"

### ISSUE THREAD

**Issue by matthiasS-da** [digital-asset/daml#14484]
In one of our CI runs, we query a transaction by id and get an exception. It is quite hard to reproduce, but maybe important nevertheless? Scenario:
- Submit a command on P1 via `CommandService.SubmitAndWaitForTransaction`.
- After the successful completion, call `GetTransactionById `, again on P1.

Stack trace:
```
java.util.NoSuchElementException: key not found: 9
	at scala.collection.immutable.BitmapIndexedMapNode.apply(HashMap.scala:635)
	at scala.collection.immutable.HashMap.apply(HashMap.scala:132)
	at com.daml.platform.store.interning.StringInterningView$$anon$1.externalize(StringInterningView.scala:69)
	at com.daml.platform.store.interning.StringInterningView$$anon$1.externalize(StringInterningView.scala:66)
	at com.daml.platform.store.interning.StringInterningDomain$$anon$1$$anon$2.externalize(StringInterning.scala:41)
	at com.daml.platform.store.interning.StringInterningDomain$$anon$1$$anon$2.externalize(StringInterning.scala:34)
	at com.daml.platform.store.interning.StringInterningDomain$$anon$1.externalize(StringInterning.scala:51)
	at com.daml.platform.store.backend.common.EventStorageBackendTemplate.$anonfun$createdTreeEventParser$1(EventStorageBackendTemplate.scala:255)
	at anorm.SqlResult.map(SqlResult.scala:13)
	at anorm.SqlResult.map$(SqlResult.scala:12)
	at anorm.Success.map(SqlResult.scala:28)
	at anorm.RowParser.$anonfun$map$1(SqlParser.scala:585)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
	at anorm.RowParser$$anon$2.apply(SqlParser.scala:555)
	at anorm.RowParser$$anon$2.apply(SqlParser.scala:554)
	at anorm.RowParser.$anonfun$$bar$1(SqlParser.scala:651)
	at anorm.RowParser$$anon$2.apply(SqlParser.scala:555)
	at anorm.RowParser$$anon$2.apply(SqlParser.scala:554)
	at anorm.Row.as(Row.scala:68)
	at anorm.Row.as$(Row.scala:67)
	at anorm.Cursor$ResultRow.as(Cursor.scala:62)
	at com.daml.platform.store.backend.common.SimpleSqlAsVectorOf$SimpleSql$u0020ops$.go$1(SimpleSqlAsVectorOf.scala:35)
	at com.daml.platform.store.backend.common.SimpleSqlAsVectorOf$SimpleSql$u0020ops$.$anonfun$asVectorOf$2(SimpleSqlAsVectorOf.scala:43)
	at anorm.Sql$.$anonfun$withResult$1(Anorm.scala:212)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
	at resource.AbstractManagedResource.$anonfun$acquireFor$1(AbstractManagedResource.scala:85)
	at scala.util.control.Exception$Catch.$anonfun$either$1(Exception.scala:251)
	at scala.util.control.Exception$Catch.apply(Exception.scala:227)
	at scala.util.control.Exception$Catch.either(Exception.scala:251)
	at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:85)
	at resource.ManagedResourceOperations$$anon$1.$anonfun$acquireFor$1(ManagedResourceOperations.scala:47)
	at resource.AbstractManagedResource.$anonfun$acquireFor$1(AbstractManagedResource.scala:85)
	at scala.util.control.Exception$Catch.$anonfun$either$1(Exception.scala:251)
	at scala.util.control.Exception$Catch.apply(Exception.scala:227)
	at scala.util.control.Exception$Catch.either(Exception.scala:251)
	at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:85)
	at resource.ManagedResourceOperations$$anon$1.acquireFor(ManagedResourceOperations.scala:47)
	at resource.DeferredExtractableManagedResource.acquireFor(AbstractManagedResource.scala:25)
	at anorm.WithResult.withResult(SqlResult.scala:172)
	at anorm.WithResult.withResult$(SqlResult.scala:172)
	at anorm.SimpleSql.withResult(SimpleSql.scala:6)
	at anorm.WithResult.withResult(SqlResult.scala:151)
	at anorm.WithResult.withResult$(SqlResult.scala:151)
	at anorm.SimpleSql.withResult(SimpleSql.scala:6)
	at com.daml.platform.store.backend.common.SimpleSqlAsVectorOf$SimpleSql$u0020ops$.asVectorOf$extension(SimpleSqlAsVectorOf.scala:43)
	at com.daml.platform.store.backend.common.EventStorageBackendTemplate.events(EventStorageBackendTemplate.scala:457)
	at com.daml.platform.store.backend.common.EventStorageBackendTemplate.transactionTree(EventStorageBackendTemplate.scala:642)
	at com.daml.platform.store.dao.events.TransactionsReader.$anonfun$lookupTransactionTreeById$1(TransactionsReader.scala:251)
	at com.daml.platform.store.dao.DataSourceConnectionProvider$$anon$2.$anonfun$runSQL$1(HikariJdbcConnectionProvider.scala:78)
	at com.daml.metrics.Timed$.$anonfun$value$1(Timed.scala:18)
	at com.codahale.metrics.Timer.time(Timer.java:118)
	at com.daml.metrics.Timed$.value(Timed.scala:18)
	at com.daml.platform.store.dao.DataSourceConnectionProvider$$anon$2.runSQL(HikariJdbcConnectionProvider.scala:78)
	at com.daml.platform.store.dao.DbDispatcherImpl.$anonfun$executeSql$2(DbDispatcher.scala:64)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

CI run: https://app.circleci.com/pipelines/github/dach-ny/canton/36921/workflows/d91c29e5-6cce-43d1-b3d3-115b95112630/jobs/766383/parallel-runs/7

Full log file (available for about 23 days): https://output.circle-artifacts.com/output/job/e66c58a8-30c5-4fb4-b0eb-4653ba9538fe/artifacts/7/log/canton_test.log.gz

DAML version: `2.4.0-snapshot.20220712.10212.0.0bf28176`

**Comment by stefanobaghino-da** [comment]
@mziolekda Is this yours?

**Comment by tudor-da** [comment]
> @mziolekda Is this yours?

Yes. We've created an internal bug tracker for it. Thanks for the ping @stefanobaghino-da

**Comment by tudor-da** [comment]
@matthiasS-da I could not reproduce it, neither in conformance test(https://github.com/digital-asset/daml/pull/14547) reproducing your described simplified scenario, neither in Canton CI in the originally observed test (https://github.com/DACH-NY/canton/compare/tudor/try-reproduce-i14484)

**Comment by tudor-da** [comment]
The logic around the potential culprit has changed significantly since the version impacted by this bug. Since it has not gone into an official release and is (so far) impossible to reproduce, I propose to keep an eye on it and update this ticket if it resurfaces.

**Comment by mziolekda** [comment]
No longer relevant, code removed
