### ISSUE TITLE
Sandbox crashes when passed in .dalf files for the "archives" parameter

### ISSUE THREAD

**Issue by da-tanabe** [digital-asset/daml#1947]
Sandbox 100.13.5 accepted .dalfs for archives, but this seems no longer possible in version 100.13.10 of the Sandbox. This should either be explicitly marked as no longer supported, or fixed (whichever was intended).

Stack trace:

```
INFO:sandbox:Sandbox verbosity changed to INFO
INFO:sandbox:Exception in thread "main" java.util.zip.ZipException: error in opening zip file
INFO:sandbox:	at java.util.zip.ZipFile.open(Native Method)
INFO:sandbox:	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
INFO:sandbox:	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
INFO:sandbox:	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
INFO:sandbox:	at com.digitalasset.platform.sandbox.stores.InMemoryPackageStore.putDarFile(InMemoryPackageStore.scala:117)
INFO:sandbox:	at com.digitalasset.platform.sandbox.SandboxServer.$anonfun$buildAndStartApiServer$1(SandboxServer.scala:168)
INFO:sandbox:	at com.digitalasset.platform.sandbox.SandboxServer.$anonfun$buildAndStartApiServer$1$adapted(SandboxServer.scala:167)
INFO:sandbox:	at scala.collection.immutable.List.foreach(List.scala:389)
INFO:sandbox:	at com.digitalasset.platform.sandbox.SandboxServer.com$digitalasset$platform$sandbox$SandboxServer$$buildAndStartApiServer(SandboxServer.scala:167)
INFO:sandbox:	at com.digitalasset.platform.sandbox.SandboxServer.start(SandboxServer.scala:272)
INFO:sandbox:	at com.digitalasset.platform.sandbox.SandboxServer.<init>(SandboxServer.scala:148)
INFO:sandbox:	at com.digitalasset.platform.sandbox.SandboxServer$.apply(SandboxServer.scala:46)
INFO:sandbox:	at com.digitalasset.platform.sandbox.SandboxMain$.$anonfun$new$2(SandboxMain.scala:22)
INFO:sandbox:	at com.digitalasset.platform.sandbox.SandboxMain$.$anonfun$new$2$adapted(SandboxMain.scala:19)
INFO:sandbox:	at scala.Option.fold(Option.scala:158)
INFO:sandbox:	at com.digitalasset.platform.sandbox.SandboxMain$.delayedEndpoint$com$digitalasset$platform$sandbox$SandboxMain$1(SandboxMain.scala:19)
INFO:sandbox:	at com.digitalasset.platform.sandbox.SandboxMain$delayedInit$body.apply(SandboxMain.scala:15)
INFO:sandbox:	at scala.Function0.apply$mcV$sp(Function0.scala:34)
INFO:sandbox:	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
INFO:sandbox:	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
INFO:sandbox:	at scala.App.$anonfun$main$1$adapted(App.scala:76)
INFO:sandbox:	at scala.collection.immutable.List.foreach(List.scala:389)
INFO:sandbox:	at scala.App.main(App.scala:76)
INFO:sandbox:	at scala.App.main$(App.scala:74)
INFO:sandbox:	at com.digitalasset.platform.sandbox.SandboxMain$.main(SandboxMain.scala:15)
INFO:sandbox:	at com.digitalasset.platform.sandbox.SandboxMain.main(SandboxMain.scala)
```

**Comment by gerolf-da** [comment]
Apologies @da-tanabe for omitting the release note entry.

@gaboraranyossy-da: In addition to amending the release notes, could you also guard `InMemoryPackageStore#putDarFile` to not crash when [loading a file](https://github.com/digital-asset/daml/blob/master/ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/stores/InMemoryPackageStore.scala#L117) as a `ZipFile` when in fact it isn't?

**Comment by gaboraranyossy-da** [comment]
Sure, will do.
