### ISSUE TITLE
damlc: no acceptable C compiler found in path

### ISSUE THREAD

**Issue by fk-da** [digital-asset/daml#23]
```
$ bazel build damlc
[dev-env] Building tools.bazel...
these derivations will be built:
  /nix/store/a794c4nz8vmqwx7vwqqnaawnavwcsim5-bazel.drv
these paths will be fetched (109.01 MiB download, 111.54 MiB unpacked):
  /nix/store/h5w8nnmbi7gw0rs57b02k8k5xxh5a779-bazel-0.22.0
copying path '/nix/store/h5w8nnmbi7gw0rs57b02k8k5xxh5a779-bazel-0.22.0' from 'http://cache.da-int.net'...
building '/nix/store/a794c4nz8vmqwx7vwqqnaawnavwcsim5-bazel.drv'...
[dev-env] Built tools.bazel in /nix/store/sfv7abpb02amwhzl0x88crj0sx0xz5ks-bazel and linked to /home/flokli/dev/daml/dev-env/var/gc-roots/bazel
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: f79fbe22-34cb-4fa2-a560-e3703b31d771
INFO: SHA256 (https://github.com/tferi-da/rules_scala/archive/b6a96474a5ee9eed0515cb0464de374e0df516f8.zip) = f953bb45ee17196a8c054786e30489e3b8764e7fbeb6d6942ac2b61b3c8f7221
DEBUG: Rule 'io_bazel_rules_scala' modified arguments {"sha256": "f953bb45ee17196a8c054786e30489e3b8764e7fbeb6d6942ac2b61b3c8f7221"}
DEBUG: /home/flokli/.cache/bazel/_bazel_flokli/69f3fdf621d09d121bb086d392d083d6/external/bazel_skylib/skylark_library.bzl:23:1: WARNING: skylark_library.bzl is deprecated and will go away in the future, please use bzl_library.bzl instead.
/nix/store/nvvmnb7qn2accgpxzbwvp5i995slycyy-bazel-cc-toolchain
WARNING: /home/flokli/dev/daml/daml-foundations/daml-ghc/package-database/BUILD.bazel:12:1: target 'ghc-prim' is both a rule and a file; please choose another name for the rule
DEBUG: /home/flokli/.cache/bazel/_bazel_flokli/69f3fdf621d09d121bb086d392d083d6/external/bazel_skylib/lib.bzl:30:1: WARNING: lib.bzl is deprecated and will go away in the future, please directly load the bzl file(s) of the module(s) needed as it is more efficient.
[dev-env] Building tools.sed...
[dev-env] Built tools.sed in /nix/store/wkgszaq2dkc4asapcbx6ypd7xdnzad9f-gnused-4.4 and linked to /home/flokli/dev/daml/dev-env/var/gc-roots/sed
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/home/flokli/.cache/bazel/_bazel_flokli/69f3fdf621d09d121bb086d392d083d6/external/haskell_network_1843485230':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
cabal2bazel: callProcess: ./configure (exit 1): failed
ERROR: Analysis of target '//:damlc' failed; build aborted: no such package '@haskell_network_1843485230//': Traceback (most recent call last):
        File "/home/flokli/.cache/bazel/_bazel_flokli/69f3fdf621d09d121bb086d392d083d6/external/ai_formation_hazel/hazel.bzl", line 19
                symlink_and_invoke_hazel(ctx, ctx.attr.hazel_base_repo_name, <4 more arguments>)
        File "/home/flokli/.cache/bazel/_bazel_flokli/69f3fdf621d09d121bb086d392d083d6/external/ai_formation_hazel/hazel_base_repository/hazel_base_repository.bzl", line 84, in symlink_and_invoke_hazel
                fail("Error running hazel on {}:\n{}\...))
Error running hazel on network.cabal:
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for gcc... no
checking for cc... no
checking for cl.exe... no

[dev-env] Building tools.sed...
[dev-env] Built tools.sed in /nix/store/wkgszaq2dkc4asapcbx6ypd7xdnzad9f-gnused-4.4 and linked to /home/flokli/dev/daml/dev-env/var/gc-roots/sed
configure: error: in `/home/flokli/.cache/bazel/_bazel_flokli/69f3fdf621d09d121bb086d392d083d6/external/haskell_network_1843485230':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
cabal2bazel: callProcess: ./configure (exit 1): failed
INFO: Elapsed time: 22.424s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (131 packages loaded, 1373 targets configured)
    currently loading: @haskell_ghc_lib__6093350//
    Fetching @haskell_network_1843485230; fetching 5s
```

**Comment by moritzkiefer-da** [comment]
Fixed in #232
