### ISSUE TITLE
Fix Scala codegen SBT examples to use codegen front-end

### ISSUE THREAD

**Issue by leo-da** [digital-asset/daml#2755]
```
leos@localhost:~/Projects/daml/language-support/scala/examples/codegen-sbt-example
$ sbt -Dda.sdk.version=100.13.21 compile
```
Gives the following error:
```
...
[error] java.lang.NoSuchMethodError: com.google.protobuf.Descriptors$FileDescriptor.internalBuildGeneratedFileFrom([Ljava/lang/String;[Lcom/google/protobuf/Descriptors$FileDescriptor;)Lcom/google/protobuf/Descriptors$FileDescriptor;
[error] 	at com.digitalasset.daml_lf.DamlLf1.<clinit>(DamlLf1.java)
[error] 	at com.digitalasset.daml_lf.DamlLf1$PrimType.getDescriptor(DamlLf1.java:359)
[error] 	at com.digitalasset.daml_lf.DamlLf1$PrimType.getValueDescriptor(DamlLf1.java:351)
```

**Comment by gerolf-da** [comment]
Closing this because we recently removed `codegen-sbt-example`.
