### ISSUE TITLE
Ledger api server indexer: Wait for index/er schema to initialize before building index server

### ISSUE THREAD

**Issue by oliverse-da** [digital-asset/daml#2974]
Proposed fix:

```
@@ -23,22 +23,16 @@ object StandaloneIndexerServer {
     val indexer =
       RecoveringIndexer(10.seconds, indexerFactory.asyncTolerance, participantId, namedLogger)

-    config.startupMode match {
-      case StartupMode.MigrateOnly =>
-        indexerFactory.migrateSchema(config.jdbcUrl)
-
-      case StartupMode.MigrateAndStart =>
-        indexer.start { actorSystem =>
-          indexerFactory
-            .migrateSchema(config.jdbcUrl)
-            .create(actorSystem, readService, config.jdbcUrl, namedLogger)
-            .flatMap(_.subscribe(readService))(DEC)
-        }
+    val initializedIndexerFactory = config.startupMode match {
+      case StartupMode.MigrateOnly | StartupMode.MigrateAndStart => indexerFactory.migrateSchema(config.jdbcUrl)
+      case StartupMode.ValidateAndStart                          => indexerFactory.validateSchema(config.jdbcUrl)
+    }

-      case StartupMode.ValidateAndStart =>
+    config.startupMode match {
+      case StartupMode.MigrateOnly => ()
+      case StartupMode.MigrateAndStart | StartupMode.ValidateAndStart =>
         indexer.start { actorSystem =>
-          indexerFactory
-            .validateSchema(config.jdbcUrl)
+          initializedIndexerFactory
             .create(actorSystem, readService, config.jdbcUrl, namedLogger)
             .flatMap(_.subscribe(readService))(DEC)
         }
```

Otherwise you can get racy failures such as

```
09:28:40.996 [sql-executor-1] ERROR c.d.c.l.a.s.p.s.s.l.s.d.HikariJdbcConnectionProvider:LedgerApiTest/participant/participant2 - Got an exception while executing a SQL query get ledger end. Rolling back the transaction.
anorm.AnormException: SqlMappingError(No rows when expecting a single one)
09:28:40.996 [sql-executor-1] ERROR c.d.c.l.a.s.p.s.s.l.s.d.HikariJdbcConnectionProvider:DomainChangeIntegrationTest/participant/participant1 - Got an exception while executing a SQL query get ledger end. Rolling back the transaction.
anorm.AnormException: SqlMappingError(No rows when expecting a single one)
09:28:41.000 [sql-executor-1] ERROR c.d.c.l.a.s.p.s.s.l.s.d.HikariJdbcConnectionProvider:AdminWorkflowTest/participant/participant1 - Got an exception while executing a SQL query get ledger end. Rolling back the transaction.
anorm.AnormException: SqlMappingError(No rows when expecting a single one)
09:28:40.996 [sql-executor-1] ERROR c.d.c.l.a.s.p.s.s.l.s.d.HikariJdbcConnectionProvider:ScenarioRunnerTest/participant/participant1 - Got an exception while executing a SQL query get ledger end. Rolling back the transaction.
anorm.AnormException: SqlMappingError(No rows when expecting a single one)
09:28:41.009 [pool-8-thread-13-ScalaTest-running-LedgerApiTest] ERROR c.d.c.l.a.s.p.i.StandaloneIndexServer:LedgerApiTest/participant/participant2 - Could not create SandboxIndexAndWriteService
anorm.AnormException: SqlMappingError(No rows when expecting a single one)
09:28:41.009 [pool-8-thread-10-ScalaTest-running-ScenarioRunnerTest] ERROR c.d.c.l.a.s.p.i.StandaloneIndexServer:ScenarioRunnerTest/participant/participant1 - Could not create SandboxIndexAndWriteService
anorm.AnormException: SqlMappingError(No rows when expecting a single one)
09:28:41.009 [pool-8-thread-9-ScalaTest-running-DomainChangeIntegrationTest] ERROR c.d.c.l.a.s.p.i.StandaloneIndexServer:DomainChangeIntegrationTest/participant/participant1 - Could not create SandboxIndexAndWriteService
anorm.AnormException: SqlMappingError(No rows when expecting a single one)
09:28:41.009 [pool-8-thread-23-ScalaTest-running-AdminWorkflowTest] ERROR c.d.c.l.a.s.p.i.StandaloneIndexServer:AdminWorkflowTest/participant/participant1 - Could not create SandboxIndexAndWriteService
anorm.AnormException: SqlMappingError(No rows when expecting a single one)
09:28:41.009 [pool-8-thread-13-ScalaTest-running-LedgerApiTest] ERROR c.d.c.p.l.a.CantonLedgerApiServerWrapper:LedgerApiTest/participant/participant2 - Failed to start ledger api server
java.lang.RuntimeException: Could not create SandboxIndexAndWriteService
	at scala.sys.package$.error(package.scala:30)
	at com.digitalasset.canton.ledger.api.server.platform.index.StandaloneIndexServer.$anonfun$buildAndStartApiServer$4(StandaloneIndexServer.scala:143)
	at scala.util.Failure.fold(Try.scala:240)
	at com.digitalasset.canton.ledger.api.server.platform.index.StandaloneIndexServer.buildAndStartApiServer(StandaloneIndexServer.scala:144)
	at com.digitalasset.canton.ledger.api.server.platform.index.StandaloneIndexServer.start(StandaloneIndexServer.scala:189)
	at com.digitalasset.canton.participant.ledger.api.CantonLedgerApiServerWrapper.$anonfun$start$2(CantonLedgerApiServerWrapper.scala:86)
	at java.util.concurrent.atomic.AtomicReference.getAndUpdate(AtomicReference.java:160)
	at com.digitalasset.canton.participant.ledger.api.CantonLedgerApiServerWrapper.$anonfun$start$1(CantonLedgerApiServerWrapper.scala:52)
	at scala.util.Try$.apply(Try.scala:213)
	at com.digitalasset.canton.participant.ledger.api.CantonLedgerApiServerWrapper.start(CantonLedgerApiServerWrapper.scala:52)
	at com.digitalasset.canton.participant.ParticipantNodeInit.idInitialized(ParticipantNode.scala:203)
```

**Comment by oliverse-da** [comment]
The above fix is not correct - I will amend it with the right fix.
