### ISSUE TITLE
sandbox 100.13.25 h2 in memory fails to start

### ISSUE THREAD

**Issue by ivan-bernikov-da** [digital-asset/daml#3055]
```
java  -jar dist/sandbox/sandbox-100.13.25.jar --sql-backend-jdbcurl jdbc:h2:mem:wall_clock_time
```
And got this error:

```
Got an exception while executing a SQL query. Rolling back the transaction.
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "PARAMETERS" not found; SQL statement:
select ledger_id from parameters [42102-198]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
```

**Comment by hurryabit** [comment]
@oliverse-da Is that one for you?

**Comment by oliverse-da** [comment]
It looks like a race condition in which the migration scripts have not run yet at the time this query is run. I have seen something similar in the DAML-on-X usage pattern related to the RecoveringIndexer startup #2974 . Not sure if that also applies to the sandbox usage?

**Comment by stefanobaghino-da** [comment]
Stale.
