### ISSUE TITLE
Perform DAML-LF name collision check in Haskell per package, not per module.

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#3252]
After a refactor of my DAML code, I'm getting this rather scary error upon submitting commands on a fresh sandbox started with
```
daml start --sandbox-option="--ledgerid=danban" --sandbox-option="-w"
```

This persists after a `daml clean`.

```
Submission of command d7be6093-df87-4d92-b2dd-3d63d1686d10 has failed.
com.digitalasset.daml.lf.validation.ECollision: null
	at com.digitalasset.daml.lf.validation.Collision$.$anonfun$checkCollisions$6(Collision.scala:35)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
	at com.digitalasset.daml.lf.validation.Collision$.$anonfun$checkCollisions$2(Collision.scala:32)
	at com.digitalasset.daml.lf.validation.Collision$.$anonfun$checkCollisions$2$adapted(Collision.scala:31)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
	at com.digitalasset.daml.lf.validation.Collision$.checkCollisions(Collision.scala:31)
	at com.digitalasset.daml.lf.validation.Collision$.$anonfun$checkPackage$2(Collision.scala:15)
	at com.digitalasset.daml.lf.validation.Collision$.$anonfun$checkPackage$2$adapted(Collision.scala:15)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:210)
	at com.digitalasset.daml.lf.validation.Collision$.checkPackage(Collision.scala:15)
	at com.digitalasset.daml.lf.validation.Validation$.checkPackage(Validation.scala:28)
	at com.digitalasset.daml.lf.validation.Validation$.checkPackage(Validation.scala:17)
	at com.digitalasset.daml.lf.speedy.Compiler.compilePackage(Compiler.scala:131)
	at com.digitalasset.daml.lf.engine.ConcurrentCompiledPackages.addPackageInternal(ConcurrentCompiledPackages.scala:60)
	at com.digitalasset.daml.lf.engine.ConcurrentCompiledPackages.addPackage(ConcurrentCompiledPackages.scala:39)
	at com.digitalasset.daml.lf.engine.Result$.$anonfun$needPackage$2(Result.scala:108)
	at com.digitalasset.daml.lf.engine.CommandPreprocessor.$anonfun$preprocessCommands$3(CommandPreprocessor.scala:225)
	at com.digitalasset.daml.lf.engine.Result.$anonfun$flatMap$2(Result.scala:37)
	at com.digitalasset.platform.sandbox.stores.ledger.CommandExecutorImpl.$anonfun$consume$3(CommandExecutorImpl.scala:107)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Unhandled internal error.
```

To reproduce, checkout branch https://github.com/bame-da/react-kanban/tree/daml-refactor/danban, start using the above command, log in as `Admin` through Navigator, and try to create a `Danban:App` with `operator = Admin`.

I don't know whether the issue is with the interpreter of the LF that's being generated so assigning  both @hurryabit and @gerolf-da .

**Comment by gerolf-da** [comment]
This shouldn't even be possible, right @remyhaemmerle-da?

**Comment by remyhaemmerle-da** [comment]
DAML-LF spec forbids such "Collision" 
See https://github.com/digital-asset/daml/blob/master/daml-lf/spec/daml-lf-1.rst#name-collision-restriction.

This check uses to be done only in the Scala side, however @associahedron implemented recently  in the Haskell side.  
This should be catch during compilation, @associahedron  ?

**Comment by associahedron** [comment]
@remyhaemmerle-da The check in the compiler operates per module only, full package name collision hasn't been implemented in the compiler yet. Shouldn't the Scala name collision checker detect this?

**Comment by remyhaemmerle-da** [comment]
@associahedron The Scala collision checker actually detects this, it is why the sandbox throws the`ECollision` error described by Bernhard.

We probably should improve the error message.

**Comment by hurryabit** [comment]
@associahedron How much work would it be to fix the check in the compiler? Is that something you can do "on the side" or does it require a lot of attention?

**Comment by associahedron** [comment]
@hurryabit It should be fixable, I'll give it a shot.
