### ISSUE TITLE
ReadOnlySqlLedger shutdown issue: Upon shutdown, catch SqlException

### ISSUE THREAD

**Issue by oliverse-da** [digital-asset/daml#3500]
Error from canton logs:

```
09:03:16.051 [sql-executor-7] ERROR c.d.p.s.s.l.s.u.SqlExecutor:AdminWorkflowTest/participant/participant2 - get_ledger_end: Got an exception while executing a SQL query. Rolled back the transaction.
java.sql.SQLException: HikariDataSource HikariDataSource (Short-Lived-Connections) has been closed.
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)
	at com.digitalasset.platform.sandbox.stores.ledger.sql.dao.HikariJdbcConnectionProvider.runSQL(HikariJdbcConnectionProvider.scala:76)
	at com.digitalasset.platform.sandbox.stores.ledger.sql.util.DbDispatcherImpl.$anonfun$executeSql$1(DbDispatcher.scala:69)
	at com.digitalasset.platform.sandbox.stores.ledger.sql.util.SqlExecutor.$anonfun$runQuery$1(SqlExecutor.scala:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
or other variant:

```
14:00:58.541 [sql-executor-11] ERROR c.d.p.s.s.l.s.u.DbDispatcher:TLSAdminApiIntegrationTest/participant/participant4 - get_ledger_end: Got an exception while executing a SQL query. Rolled back the transaction.
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1571)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1547)
	at org.h2.jdbc.JdbcConnection.setAutoCommit(JdbcConnection.java:500)
	at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:388)
	at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java)
	at com.digitalasset.platform.sandbox.stores.ledger.sql.dao.HikariJdbcConnectionProvider.runSQL(HikariJdbcConnectionProvider.scala:85)
	at com.digitalasset.platform.sandbox.stores.ledger.sql.util.DbDispatcher.$anonfun$executeSql$1(DbDispatcher.scala:56)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:658)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The most likely caller seems to be ReadOnlySqlLedger.ledgerEndUpdateKillSwitch:

```
private class ReadOnlySqlLedger(
    ledgerId: LedgerId,
    headAtInitialization: Long,
    ledgerDao: LedgerReadDao)(implicit mat: Materializer)
    extends BaseLedger(ledgerId, headAtInitialization, ledgerDao) {

  private val ledgerEndUpdateKillSwitch = {
    val offsetUpdates = Source
      .tick(0.millis, 100.millis, ())
      .mapAsync(1)(_ => ledgerDao.lookupLedgerEnd())

    RestartSource
      .withBackoff(
        minBackoff = 1.second,
        maxBackoff = 10.seconds,
        randomFactor = 0.2
      )(() => offsetUpdates)
      .viaMat(KillSwitches.single)(Keep.right[NotUsed, UniqueKillSwitch])
      .to(Sink.foreach(dispatcher.signalNewHead))
      .run()
  }

  override def close(): Unit = {
    ledgerEndUpdateKillSwitch.shutdown()
    super.close()
  }
}
```

Here is the most recent incarnation of what looks to be the same phenomenon except manifesting itself in terms of the execution context being close already during the akka flow activity in the `offsetUpdates` above: 

```
java.util.concurrent.RejectedExecutionException: Task scala.concurrent.impl.CallbackRunnable@64074a30 rejected from java.util.concurrent.ThreadPoolExecutor@2105d8d4[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 13]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:372)
	at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete$(Promise.scala:371)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.onComplete(Promise.scala:379)
	at scala.concurrent.impl.Promise.transform(Promise.scala:33)
	at scala.concurrent.impl.Promise.transform$(Promise.scala:31)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.transform(Promise.scala:379)
	at scala.concurrent.Future.map(Future.scala:292)
	at scala.concurrent.Future.map$(Future.scala:292)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.map(Promise.scala:379)
	at scala.concurrent.Future$.apply(Future.scala:658)
	at com.digitalasset.platform.sandbox.stores.ledger.sql.util.DbDispatcher.executeSql(DbDispatcher.scala:84)
	at com.digitalasset.platform.sandbox.stores.ledger.sql.dao.JdbcLedgerDao.lookupLedgerEnd(JdbcLedgerDao.scala:112)
	at com.digitalasset.platform.sandbox.stores.ledger.sql.dao.MeteredLedgerReadDao.$anonfun$lookupLedgerEnd$1(MeteredLedgerDao.scala:56)
	at com.digitalasset.platform.sandbox.metrics.package$.timedFuture(package.scala:14)
	at com.digitalasset.platform.sandbox.stores.ledger.sql.dao.MeteredLedgerReadDao.lookupLedgerEnd(MeteredLedgerDao.scala:56)
	at com.digitalasset.platform.sandbox.stores.ledger.sql.ReadOnlySqlLedger.$anonfun$ledgerEndUpdateKillSwitch$1(ReadOnlySqlLedger.scala:66)
	at akka.stream.impl.fusing.MapAsyncUnordered$$anon$31.onPush(Ops.scala:1375)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:495)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:624)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:501)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:599)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:768)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:783)
	at akka.actor.Actor.aroundReceive(Actor.scala:533)
	at akka.actor.Actor.aroundReceive$(Actor.scala:531)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:690)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:573)
	at akka.actor.ActorCell.invoke(ActorCell.scala:543)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
^^^ from canton test run 64657

**Comment by oliverse-da** [comment]
Also @matthiasS-da noted that the exception is logged to stdout https://github.com/DACH-NY/canton/issues/2691 - perhaps as a side effect of not being caught - perhaps akka logs this to stdout.
