### ISSUE TITLE
DAML Studio: non-terminating recursive calls get scenario service stuck

### ISSUE THREAD

**Issue by circlespainter** [digital-asset/daml#3643]
When calling a non-terminating recursive function in an action, e.g.:

```
recF : Int -> Int
recF x = recF x
```

`scenario-service.jar` spins the CPU even before running the scenario and killing it won't help as it will re-spawn, the only way to get rid of it is closing VSCode. The following IDE problem are displayed:

```
{
	"resource": "/home/fabio/Study/Self-study/DAML/quickstart-scala/daml/Tests/Iou.daml",
	"owner": "_generated_diagnostic_collection_name_#1",
	"severity": 8,
	"message": "\"Scenario service backend error: BErrorClient (ClientIOError (GRPCIOBadStatusCode StatusDeadlineExceeded (StatusDetails {unStatusDetails = \\\"Deadline Exceeded\\\"})))\"",
	"source": "Scenario",
	"startLineNumber": 9,
	"startColumn": 1,
	"endLineNumber": 9,
	"endColumn": 9
}
```

```
damlc: user error (Scenario service exited unexpectedly)
[Info  - 8:46:22] Connection to server got closed. Server will restart.
[Error - 8:46:22] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/fabio/.vscode/extensions/digitalassetholdingsllc.daml-0.13.37/node_modules/vscode-jsonrpc/lib/main.js:902:25)
	at Object.dispose (/home/fabio/.vscode/extensions/digitalassetholdingsllc.daml-0.13.37/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/home/fabio/.vscode/extensions/digitalassetholdingsllc.daml-0.13.37/node_modules/vscode-languageclient/lib/client.js:2236:42)
	at LanguageClient.handleConnectionClosed (/home/fabio/.vscode/extensions/digitalassetholdingsllc.daml-0.13.37/node_modules/vscode-languageclient/lib/main.js:154:15)
	at closeHandler (/home/fabio/.vscode/extensions/digitalassetholdingsllc.daml-0.13.37/node_modules/vscode-languageclient/lib/client.js:2223:18)
	at CallbackList.invoke (/home/fabio/.vscode/extensions/digitalassetholdingsllc.daml-0.13.37/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/fabio/.vscode/extensions/digitalassetholdingsllc.daml-0.13.37/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/home/fabio/.vscode/extensions/digitalassetholdingsllc.daml-0.13.37/node_modules/vscode-jsonrpc/lib/main.js:238:26)
	at CallbackList.invoke (/home/fabio/.vscode/extensions/digitalassetholdingsllc.daml-0.13.37/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/fabio/.vscode/extensions/digitalassetholdingsllc.daml-0.13.37/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at StreamMessageReader.fireClose (/home/fabio/.vscode/extensions/digitalassetholdingsllc.daml-0.13.37/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.<anonymous> (/home/fabio/.vscode/extensions/digitalassetholdingsllc.daml-0.13.37/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:205:15)
	at Pipe.<anonymous> (net.js:586:12)
```

**Comment by circlespainter** [comment]
VSCode 1.40.1 on Linux Ubuntu 19.10 (x64), DAML SDK 0.13.37

**Comment by cocreature** [comment]
Thanks for the report, this is an instance of the more general feature of limiting the execution resources of a transaction. For scenarios an infinite loop is mostly annoying but for an actual transaction on the ledger that is an attack vector. We are planning to address this over the next months.
