### ISSUE TITLE
RecoveringIndexer no longer recovers after a failure of the transaction source

### ISSUE THREAD

**Issue by mziolekda** [digital-asset/daml#3945]
When an akka source created in stateUpdates call to ReadService terminates with an exception, indexer prints following message:

```
13:48:04.933 ERROR c.d.p.i.RecoveringIndexer:participant/daml_ledger_api1 - Error while running indexer, restart scheduled after 10 seconds
io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED
        at io.grpc.Status.asRuntimeException(Status.java:533)
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
```

After aforementioned 10 seconds, it initiates a restart:

```
13:48:14.971 INFO  c.d.p.i.RecoveringIndexer:participant/daml_ledger_api1 - Starting Indexer Server
13:48:14.974 INFO  c.z.h.HikariDataSource - Short-Lived-Connections - Starting...
```

This is the last message ever printed by the indexer. The execution gets stuck somewhere before the call to ReadService.stateUpdates. In my implementation of that method I added a logline at the beginning like so:

```
override def stateUpdates(beginAfter: Option[Offset]): Source[(Offset, Update), NotUsed] = {
    logger.info(s"Initializing transaction source")
``` 

This message is not printed on a restart.

This functionality used to work in the past.

**Comment by mziolekda** [comment]
Recovering Indexer works again in the SDK version 0.13.46
