### ISSUE TITLE
Fix blinking ScalaCodegenIt

### ISSUE THREAD

**Issue by leo-da** [digital-asset/daml#44]
It just blinked in my PR with totally unrelated changes:
```
ScalaCodeGenIT:
- generated package ID among those returned by the packageClient (665 milliseconds)
- alice creates CallablePayout contract and receives corresponding event *** FAILED *** (10 seconds, 179 milliseconds)
  A timeout occurred waiting for a future to complete. Queried 40 times, sleeping 250 milliseconds between each query. (ScalaCodeGenIT.scala:323)
  org.scalatest.concurrent.Futures$FutureConcept$$anon$1:
  at org.scalatest.concurrent.Futures$FutureConcept.tryTryAgain$1(Futures.scala:538)
  at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl(Futures.scala:550)
  at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl$(Futures.scala:479)
  at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
```

**Comment by leo-da** [comment]
Can't reproduce it. The test has been stable. I ran it multiple times plus I don't remember anyone complaining about this particular test in the last 3-4 weeks. The reported timeout might have been caused by some instabilities in sandbox or other component used in the test.
