### ISSUE TITLE
gRPC Recursion Limit

### ISSUE THREAD

**Issue by apeacock-da** [digital-asset/daml#46]
Long scenarios fail with the below:
```
Waiting for Sandbox................Failed to start sandbox-java
Description: user error (Unable to connect to Sandbox on port 7600: timeout after 15 seconds)
Error type: SomeException
------ last 20 lines from log ------
    at com.digitalasset.daml_lf.DamlLf1$CaseAlt$1.parsePartialFrom(DamlLf1.java:42673)
    at com.digitalasset.daml_lf.DamlLf1$CaseAlt$1.parsePartialFrom(DamlLf1.java:42668)
    at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:911)
    at com.digitalasset.daml_lf.DamlLf1$Case.<init>(DamlLf1.java:42816)
    at com.digitalasset.daml_lf.DamlLf1$Case.<init>(DamlLf1.java:42760)
    at com.digitalasset.daml_lf.DamlLf1$Case$1.parsePartialFrom(DamlLf1.java:43725)
    at com.digitalasset.daml_lf.DamlLf1$Case$1.parsePartialFrom(DamlLf1.java:43720)
    at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:911)
    at com.digitalasset.daml_lf.DamlLf1$Expr.<init>(DamlLf1.java:22608)
    at com.digitalasset.daml_lf.DamlLf1$Expr.<init>(DamlLf1.java:22394)
    at com.digitalasset.daml_lf.DamlLf1$Expr$1.parsePartialFrom(DamlLf1.java:39643)
    at com.digitalasset.daml_lf.DamlLf1$Expr$1.parsePartialFrom(DamlLf1.java:39638)
    at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:911)
    at com.digitalasset.daml_lf.DamlLf1$CaseAlt.<init>(DamlLf1.java:39836)
    at com.digitalasset.daml_lf.DamlLf1$CaseAlt.<init>(DamlLf1.java:39733)
    at com.digitalasset.daml_lf.DamlLf1$CaseAlt$1.parsePartialFrom(DamlLf1.java:42673)
    at com.digitalasset.daml_lf.DamlLf1$CaseAlt$1.parsePartialFrom(DamlLf1.java:42668)
    at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:911)
    at com.digitalasset.daml_lf.DamlLf1$Case.<init>(DamlLf1.java:42816)
    at com.digitalasset.daml_lf.DamlLf1$Case.<init>(DamlLf1.java:42760)
```
The actual error is:

> com.google.protobuf.InvalidProtocolBufferException: Protocol message had too many levels of nesting.  May be malicious.  Use CodedInputStream.setRecursionLimit() to increase the depth limit.

The solution is to either increase the recursion limit or refactor the data structures not to be so right-tailed.

**Comment by stefanobaghino-da** [comment]
@remyhaemmerle-da Does this issue still stand?

**Comment by remyhaemmerle-da** [comment]
unfortunately yes.

**Comment by roger-bosman-da** [comment]
fixed by [#21155](https://github.com/digital-asset/daml/issues/21155)
