### ISSUE TITLE
Connection reset exception when calling daml start

### ISSUE THREAD

**Issue by rohanjr** [digital-asset/daml#4670]
We are running `daml start` in the https://github.com/digital-asset/create-daml-app project with the following command
```
daml start \
  --open-browser=no \
  --start-navigator=no \
  --sandbox-option=--wall-clock-time \
  --sandbox-option='--ledgerid=create-daml-app-sandbox'
```

In some cases, we get the following error
```
..........Waiting for JSON API to start: 
Feb 24, 2020 3:29:22 PM io.grpc.netty.NettyServerTransport notifyTerminated
INFO: Transport failed
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:345)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:376)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1140)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:830)
```
The sandbox seems to start up ok before this, and the JSON API server is even able to connect after the error is shown. So in the end the exception is benign but still unfriendly for users (especially those using the Getting Started guide).

CC @nemanja-da @hurryabit @stefanobaghino-da @gerolf-da

**Comment by hurryabit** [comment]
On MacOS, I can reproduce it with openjdk13 but not with openjdk12.
