### ISSUE TITLE
Investigate why Synchronous API logs `java.util.NoSuchElementException: key not found`

### ISSUE THREAD

**Issue by leo-da** [digital-asset/daml#4761]
Follow the dagger quickstart: https://github.com/DACH-NY/dagger to reproduce the error.
Creating a `PostPaymentIntents` contract through the navigator (this will result in a `PostPaymentIntentsResponse` which should trigger the error).

```
java.util.NoSuchElementException: key not found: TemplateId(9d2a07f50e31b04e5d651fb3cf9110d1dbfd80c25d964b96922448dc988787f9,StripeAPI,PostPaymentIntentsResponse)
	at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:98)
	at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:96)
	at com.digitalasset.http.ContractsService.$anonfun$searchInMemory$6(ContractsService.scala:255)
	at com.digitalasset.http.ContractsService.$anonfun$searchInMemory$6$adapted(ContractsService.scala:254)
	at scala.collection.TraversableLike.$anonfun$filterImpl$1(TraversableLike.scala:248)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:247)
	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:104)
	at scala.collection.TraversableLike.filter(TraversableLike.scala:259)
	at scala.collection.TraversableLike.filter$(TraversableLike.scala:259)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
	at com.digitalasset.http.ContractsService.$anonfun$searchInMemory$2(ContractsService.scala:254)
	at akka.stream.impl.fusing.Map$$anon$1.onPush(Ops.scala:54)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:624)
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute(ActorGraphInterpreter.scala:55)
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute$(ActorGraphInterpreter.scala:51)
	at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnNext.execute(ActorGraphInterpreter.scala:94)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:599)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:768)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:783)
	at akka.actor.Actor.aroundReceive(Actor.scala:533)
	at akka.actor.Actor.aroundReceive$(Actor.scala:531)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:690)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:573)
	at akka.actor.ActorCell.invoke(ActorCell.scala:543)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by leo-da** [comment]
Luciano  1 day ago
Hi, I'm seeing some strange behaviour ... I'm seeing
11:18:22.733 [http-json-ledger-api-akka.actor.default-dispatcher-5] ERROR com.digitalasset.http.Endpoints - Source failed
java.util.NoSuchElementException: key not found: TemplateId(9d2a07f50e31b04e5d651fb3cf9110d1dbfd80c25d964b96922448dc988787f9,StripeAPI,PostPaymentIntentsResponse)
However, everything seems to work fine in my app.
I think this began happening since I changed the JWT token I'm passing from the old to the new format, but I could be wrong.

Luciano  1 day ago
I can also confirm this is an existing template.

leo  1 day ago
Hi @Luciano
Questions:
Do you have the entire stack trace for the error?
You are using streaming API, everything works as expected, but you see this error in the log, right?
Please provide steps to reproduce the error

Luciano  7 hours ago
Hi Leo,
Yes, I'll paste it below.
Do you mean by 'streaming' the websocket endpoint? No, I'm just using the REST endpoint.
You can reproduce this by following the quickstart here: https://github.com/DACH-NY/dagger
And creating a PostPaymentIntents contract through the navigator (this will result in a PostPaymentIntentsResponse which should trigger the error).
stack trace:
```
java.util.NoSuchElementException: key not found: TemplateId(9d2a07f50e31b04e5d651fb3cf9110d1dbfd80c25d964b96922448dc988787f9,StripeAPI,PostPaymentIntentsResponse)
	at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:98)
	at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:96)
	at com.digitalasset.http.ContractsService.$anonfun$searchInMemory$6(ContractsService.scala:255)
	at com.digitalasset.http.ContractsService.$anonfun$searchInMemory$6$adapted(ContractsService.scala:254)
	at scala.collection.TraversableLike.$anonfun$filterImpl$1(TraversableLike.scala:248)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:247)
	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:104)
	at scala.collection.TraversableLike.filter(TraversableLike.scala:259)
	at scala.collection.TraversableLike.filter$(TraversableLike.scala:259)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
	at com.digitalasset.http.ContractsService.$anonfun$searchInMemory$2(ContractsService.scala:254)
	at akka.stream.impl.fusing.Map$$anon$1.onPush(Ops.scala:54)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:624)
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute(ActorGraphInterpreter.scala:55)
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute$(ActorGraphInterpreter.scala:51)
	at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnNext.execute(ActorGraphInterpreter.scala:94)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:599)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:768)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:783)
	at akka.actor.Actor.aroundReceive(Actor.scala:533)
	at akka.actor.Actor.aroundReceive$(Actor.scala:531)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:690)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:573)
	at akka.actor.ActorCell.invoke(ActorCell.scala:543)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by leo-da** [comment]
`funPredicates(ac.templateId)` throws. Need to understand how we ended up with unknown `domain.TemplateId.RequiredPkg`.

```
          converted copy (inserts = converted.inserts filter (ac =>
            funPredicates(ac.templateId)(ac.payload))),
```
which is defined like:
```
    val funPredicates: Map[domain.TemplateId.RequiredPkg, LfValue => Boolean] =
      templateIds.map(tid => (tid, valuePredicate(tid, queryParams).toFunPredicate))(breakOut)
```

**Comment by leo-da** [comment]
hi @lJoublanc  

can you provide steps to reproduce in terms of JSON API commands, I have tried to follow dagger quickstart instructions:

```
cd ~/src
git clone https://github.com/lucianojoublanc-da/openapi stripe-openapi
cd ~/src/lib-message-integration/tool-metagen
```
```
leos@localhost:~/Projects/dagger/src
$ cd ~/src/lib-message-integration/tool-metagen
bash: cd: /home/leos/src/lib-message-integration/tool-metagen: No such file or directory
```
It looks too me that `dagger` using unknown `TemplateId` in one of the following calls to the JSON API:
- `/v1/fetch` or
- `/v1/query`

**Comment by leo-da** [comment]
One more thing, make sure that you are not running JSON API with `package-reload-interval` set to something like 1hr :)

If you upload a new template, create a contract via the Navigator and try to query the contract using JSON API, the JSON API may not know about the new contract template, but default it asks for package updates every 5 sec:

```
  --package-reload-interval <value>
        Optional interval to poll for package updates. Examples: 500ms, 5s, 10min, 1h, 1d. Defaults to 5 seconds
```

**Comment by leo-da** [comment]
the above PR should fix the error in the log

**Comment by lJoublanc** [comment]
Hi Leo,

I used wireshark to capture the messages. I can send you the dump file (rather not post it here though). I've noticed that every time this error pops up appears to be on the query for a specific template. All the messages I see look like this:

```
POST /v1/query HTTP/1.1
Content-Length: 49
Host: localhost:7575
User-Agent: Java-http-client/11.0.6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwczovL2RhbWwuY29tL2xlZGdlci1hcGkiOnsibGVkZ2VySWQiOiJNeUxlZGdlciIsImFwcGxpY2F0aW9uSWQiOiJmb29iYXIiLCJhY3RBcyI6WyJBbGljZSJdfX0.VdDI96mw5hrfM5ZNxLyetSVwcD7XtLT4dIdHIOa9lcU
Content-Type: application/json

{"templateIds":["StripeAPI:GetCheckoutSessions"]}

HTTP/1.1 200 OK
Server: akka-http/10.1.11
Date: Wed, 04 Mar 2020 07:42:13 GMT
Connection: close
Content-Type: application/json

{"warnings":{"unknownTemplateIds":["StripeAPI:GetCheckoutSessions"]},"result":[],"errors":["Endpoints.ServerError: java.util.NoSuchElementException: key not found: TemplateId(9d2a07f50e31b04e5d651fb3cf9110d1dbfd80c25d964b96922448dc988787f9,StripeAPI,PostPaymentIntentsResponse)"],"status":501}
```

i.e. They all appear when I query `GetCheckoutSessions`.

And when I tried to verify that it exists, I can't see it on the ledger (note the first one ends `SessionsSession` - it's not the same). 

![image](https://user-images.githubusercontent.com/6293472/75857042-d62f0d80-5df5-11ea-8d01-921ced7cac19.png)

So that is clearly __a bug in my program__. However, it doesn't really explain the error message. Is it possible that you're just printing out the wrong template name somehow, in the error message?

I can send you the whole dump file, if that helps - slack me when you're available.

**Comment by lJoublanc** [comment]
> One more thing, make sure that you are not running JSON API with `package-reload-interval` set to something like 1hr :)

Using these startup arguments:
```
( sleep 10 && daml json-api --max-inbound-message-size 30000000 --ledger-host localhost --ledger-port 6865 --http-port 7575 )
```

**Comment by leo-da** [comment]
@lJoublanc check the JSON API log for INFO entry: `new package IDs loaded: ...`
Let's schedule a zoom debug session.

**Comment by leo-da** [comment]
@lJoublanc 
Regarding this output:
```
{"warnings":{"unknownTemplateIds":["StripeAPI:GetCheckoutSessions"]},"result":[],"errors":["Endpoints.ServerError: java.util.NoSuchElementException: key not found: TemplateId(9d2a07f50e31b04e5d651fb3cf9110d1dbfd80c25d964b96922448dc988787f9,StripeAPI,PostPaymentIntentsResponse)"],"status":501}
```

JSON API could not resolve `StripeAPI:GetCheckoutSessions` template ID, this means that the corresponding package has not been loaded yet or you have two versions of this template loaded from two different packages (with two different package IDs).

the fix for `java.util.NoSuchElementException:` is in the master, this was a JSON API bug. Thanks for bringing it up.

**Comment by leo-da** [comment]
@lJoublanc if it is still an issue let's have a zoom. Else can we close it?

**Comment by leo-da** [comment]
I am going to close this issue.
