### ISSUE TITLE
Ledger API server crashes with metric clash in docker container on GCP VM

### ISSUE THREAD

**Issue by fabiotudone-da** [digital-asset/daml#5428]
This one seems timing-dependent and, specifically, only seem to happen when starting a container that runs the API server in a VM in GCP. It's not triggered when running it as a JAR directly in the VM and when starting the container, then connecting to it and launching the JAR.

Version: `100.13.56-snapshot.20200325.3626.0.a3ddde3a`.

```
07:01:48.459 ERROR c.d.p.i.RecoveringIndexer - Error while starting indexer, restart scheduled after 10 seconds
java.lang.IllegalArgumentException: A metric named daml.index.db.connection.indexer.pool.TotalConnections already exists
	at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:156)
	at com.zaxxer.hikari.metrics.dropwizard.CodaHaleMetricsTracker.<init>(CodaHaleMetricsTracker.java:59)
	at com.zaxxer.hikari.metrics.dropwizard.CodahaleMetricsTrackerFactory.create(CodahaleMetricsTrackerFactory.java:41)
	at com.zaxxer.hikari.pool.HikariPool.setMetricsTrackerFactory(HikariPool.java:302)
	at com.zaxxer.hikari.pool.HikariPool.setMetricRegistry(HikariPool.java:284)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:121)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at com.digitalasset.platform.store.dao.HikariConnection$.$anonfun$owner$1(HikariJdbcConnectionProvider.scala:49)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by fabiotudone-da** [comment]
@mziolekda @SamirTalwar-DA I think we can close this one

**Comment by SamirTalwar-DA** [comment]
Yeah, this one has been fixed for quite some time.
