### ISSUE TITLE
Scenario service backend error: ClientIOError GRPCIOBadStatusCode StatusUnknown

### ISSUE THREAD

**Issue by richardkapolnai-da** [digital-asset/daml#5725]
`daml test` should give the following result for this input: `Commit error due to unique key violation for key` . However, I got:
```
File:     daml/KeyViolation.daml
Hidden:   no
Range:    31:0-31:4
Source:   Scenario
Severity: DsError
Message: 
  "Scenario service backend error: BErrorClient (ClientIOError (GRPCIOBadStatusCode StatusUnknown
  (StatusDetails {unStatusDetails = \"\"})))"

2020-04-24 17:10:33.91 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: Apr 24, 2020 7:10:33 PM io.grpc.internal.SerializingExecutor run

2020-04-24 17:10:33.91 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@2b1ffd3e

2020-04-24 17:10:33.91 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: java.util.NoSuchElementException: key not found: AbsoluteContractId(00757512e24aa519f56467262dc7c2ad954fa74f8030db82e4ad431eb470f8fc5f)

2020-04-24 17:10:33.91 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:98)

2020-04-24 17:10:33.91 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:96)

2020-04-24 17:10:33.91 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at com.daml.lf.scenario.Conversions.convertContractId(Conversions.scala:309)

2020-04-24 17:10:33.91 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at com.daml.lf.scenario.Conversions.convertTxNode(Conversions.scala:527)

2020-04-24 17:10:33.91 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at com.daml.lf.scenario.Conversions.$anonfun$convertPartialTransaction$1(Conversions.scala:377)

2020-04-24 17:10:33.91 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at scala.Function$.$anonfun$tupled$1(Function.scala:77)

2020-04-24 17:10:33.91 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)

2020-04-24 17:10:33.91 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:231)

2020-04-24 17:10:33.91 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:462)

2020-04-24 17:10:33.91 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:462)

2020-04-24 17:10:33.91 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at scala.collection.TraversableLike.map(TraversableLike.scala:234)

2020-04-24 17:10:33.92 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)

2020-04-24 17:10:33.92 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)

2020-04-24 17:10:33.92 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at com.daml.lf.scenario.Conversions.convertPartialTransaction(Conversions.scala:377)

2020-04-24 17:10:33.92 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at com.daml.lf.scenario.Conversions.convertScenarioError(Conversions.scala:69)

2020-04-24 17:10:33.92 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at com.daml.lf.scenario.ScenarioService.$anonfun$runScenario$2(ScenarioServiceMain.scala:96)

2020-04-24 17:10:33.92 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at scala.Option.map(Option.scala:146)

2020-04-24 17:10:33.93 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at com.daml.lf.scenario.ScenarioService.$anonfun$runScenario$1(ScenarioServiceMain.scala:89)

2020-04-24 17:10:33.93 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at scala.Option.flatMap(Option.scala:171)

2020-04-24 17:10:33.93 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at com.daml.lf.scenario.ScenarioService.runScenario(ScenarioServiceMain.scala:76)

2020-04-24 17:10:33.93 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at com.daml.lf.scenario.api.v1.ScenarioServiceGrpc$MethodHandlers.invoke(ScenarioServiceGrpc.java:643)

2020-04-24 17:10:33.93 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)

2020-04-24 17:10:33.93 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)

2020-04-24 17:10:33.93 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:808)

2020-04-24 17:10:33.93 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)

2020-04-24 17:10:33.93 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)

2020-04-24 17:10:33.93 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

2020-04-24 17:10:33.93 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

2020-04-24 17:10:33.93 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at java.base/java.lang.Thread.run(Thread.java:834)

2020-04-24 17:10:33.93 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 
File:     daml/PingPong.daml
Hidden:   no
Range:    35:0-35:4
Source:   Scenario
Severity: DsError
Message: 
  "Scenario service backend error: BErrorClient (ClientIOError (GRPCIOBadStatusCode StatusUnknown
  (StatusDetails {unStatusDetails = \"\"})))"

2020-04-24 17:10:34.58 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: Apr 24, 2020 7:10:34 PM io.grpc.internal.SerializingExecutor run

2020-04-24 17:10:34.58 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@7874dc1f

2020-04-24 17:10:34.59 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: java.util.NoSuchElementException: key not found: AbsoluteContractId(005f143bcd58d24c31222e13c6b20bd9b20f64bbb94f4cbce97fc108b214c3bd37)

2020-04-24 17:10:34.59 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:98)

2020-04-24 17:10:34.59 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:96)

2020-04-24 17:10:34.59 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at com.daml.lf.scenario.Conversions.convertContractId(Conversions.scala:309)

2020-04-24 17:10:34.59 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 	at com.daml.lf.scenario.Conversions.convertTxNode(Conversions.scala:527)

2020-04-24 17:10:34.59 [ERR
```

the input was:

```
module KeyViolation where

template Ping
  with
    party : Party
  where
    signatory party
    key party: Party
    maintainer key

    controller party can
      ArchivePong : ()
        with
          pong : ContractId Pong
        do
          exercise pong Archive

template Pong
  with
    party : Party
  where
    signatory party

    controller party can
      ArchivePing : ()
        with
          pingParty : Party
        do
          exerciseByKey @Ping pingParty Archive

test = scenario do
  party <- getParty "party"

  submit party do
    ping1 <- create Ping with party
    ping2 <- create Ping with party
    pong1 <- create Pong with party
    exercise ping1 ArchivePong with pong = pong1
```

When the last line is replace by `pure ()`, then the error message goes back to normal.

**Comment by cocreature** [comment]
This issue has been fixed already and the fix will be included in 1.0.1 which is expected to be released today. You can try the latest snapshot which produces the correct error:
```
DAML_SDK_VERSION=1.0.0-snapshot.20200424.3917.0.16093690 daml damlc test --files ~/tmp/KeyViolation.daml
```
