### ISSUE TITLE
My application hang on `submitAndWait` and noticed Sandbox-classic logs NPE

### ISSUE THREAD

**Issue by dsun-da** [digital-asset/daml#6064]
Here is the stacktrace

```
00:24:25.919 [sandbox-akka.actor.default-dispatcher-28] ERROR c.d.p.a.s.ApiSubmissionService - Unhandled internal error (context: {participantId=sandbox-participant, commandId=232e45c7-3892-469a-8217-7c15f735ac19, parties=[00001]}) 
java.lang.NullPointerException: null
	at scala.collection.immutable.ListMap$Node.$plus(ListMap.scala:174)
	at scala.collection.immutable.HashMap$HashMapCollision1.updated0(HashMap.scala:425)
	at scala.collection.immutable.HashMap$HashMapCollision1.merge0(HashMap.scala:481)
	at scala.collection.immutable.HashMap$HashTrieMap.mergeMaybeSubset$1(HashMap.scala:748)
	at scala.collection.immutable.HashMap$HashTrieMap.merge0(HashMap.scala:876)
	at scala.collection.immutable.HashMap$HashTrieMap.mergeMaybeSubset$1(HashMap.scala:748)
	at scala.collection.immutable.HashMap$HashTrieMap.merge0(HashMap.scala:876)
	at scala.collection.immutable.HashMap$HashTrieMap.mergeMaybeSubset$1(HashMap.scala:748)
	at scala.collection.immutable.HashMap$HashTrieMap.merge0(HashMap.scala:876)
	at scala.collection.immutable.HashMap$HashTrieMap.mergeMaybeSubset$1(HashMap.scala:748)
	at scala.collection.immutable.HashMap$HashTrieMap.merge0(HashMap.scala:877)
	at scala.collection.immutable.HashMap.merged(HashMap.scala:137)
	at scala.collection.immutable.HashMap.$plus$plus(HashMap.scala:184)
	at scala.collection.immutable.HashMap.$plus$plus(HashMap.scala:173)
	at com.daml.platform.sandbox.stores.InMemoryActiveLedgerState.divulgeAlreadyCommittedContracts(InMemoryActiveLedgerState.scala:138)
	at com.daml.platform.sandbox.stores.InMemoryActiveLedgerState.divulgeAlreadyCommittedContracts(InMemoryActiveLedgerState.scala:21)
	at com.daml.platform.store.ActiveLedgerStateManager.$anonfun$addTransaction$15(ActiveLedgerStateManager.scala:220)
	at scala.Option.map(Option.scala:230)
	at com.daml.platform.store.ActiveLedgerStateManager$AddTransactionState.mapAcs(ActiveLedgerStateManager.scala:34)
	at com.daml.platform.store.ActiveLedgerStateManager.addTransaction(ActiveLedgerStateManager.scala:220)
	at com.daml.platform.sandbox.stores.InMemoryActiveLedgerState.addTransaction(InMemoryActiveLedgerState.scala:167)
	at com.daml.platform.sandbox.stores.ledger.inmemory.InMemoryLedger.$anonfun$handleSuccessfulTx$2(InMemoryLedger.scala:323)
	at com.daml.platform.sandbox.stores.ledger.inmemory.InMemoryLedger.$anonfun$handleSuccessfulTx$2$adapted(InMemoryLedger.scala:307)
	at scala.util.Either.fold(Either.scala:191)
	at com.daml.platform.sandbox.stores.ledger.inmemory.InMemoryLedger.handleSuccessfulTx(InMemoryLedger.scala:307)
	at com.daml.platform.sandbox.stores.ledger.inmemory.InMemoryLedger.publishTransaction(InMemoryLedger.scala:282)
	at com.daml.platform.sandbox.stores.ledger.MeteredLedger.$anonfun$publishTransaction$1(MeteredLedger.scala:27)
	at com.daml.metrics.Timed$.future(Timed.scala:30)
	at com.daml.platform.sandbox.stores.ledger.MeteredLedger.publishTransaction(MeteredLedger.scala:27)
	at com.daml.platform.sandbox.stores.LedgerBackedWriteService.submitTransaction(SandboxIndexAndWriteService.scala:180)
	at com.daml.ledger.participant.state.v1.metrics.TimedWriteService.$anonfun$submitTransaction$1(TimedWriteService.scala:23)
	at com.daml.metrics.Timed$.completionStage(Timed.scala:22)
	at com.daml.ledger.participant.state.v1.metrics.TimedWriteService.submitTransaction(TimedWriteService.scala:23)
	at com.daml.platform.apiserver.services.ApiSubmissionService.submitTransaction(ApiSubmissionService.scala:268)
	at com.daml.platform.apiserver.services.ApiSubmissionService.submitTransaction(ApiSubmissionService.scala:251)
	at com.daml.platform.apiserver.services.ApiSubmissionService.$anonfun$recordOnLedger$5(ApiSubmissionService.scala:203)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:47)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:47)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
00:24:25.920 [sandbox-akka.actor.default-dispatcher-21] WARN  c.d.l.c.s.c.tracker.CommandTracker - Service responded with error for submitting command with context (Future(<not completed>),232e45c7-3892-469a-8217-7c15f735ac19). Status of command is unknown. watching for completion... 
java.lang.NullPointerException: null
	at scala.collection.immutable.ListMap$Node.$plus(ListMap.scala:174)
	at scala.collection.immutable.HashMap$HashMapCollision1.updated0(HashMap.scala:425)
	at scala.collection.immutable.HashMap$HashMapCollision1.merge0(HashMap.scala:481)
	at scala.collection.immutable.HashMap$HashTrieMap.mergeMaybeSubset$1(HashMap.scala:748)
	at scala.collection.immutable.HashMap$HashTrieMap.merge0(HashMap.scala:876)
	at scala.collection.immutable.HashMap$HashTrieMap.mergeMaybeSubset$1(HashMap.scala:748)
	at scala.collection.immutable.HashMap$HashTrieMap.merge0(HashMap.scala:876)
	at scala.collection.immutable.HashMap$HashTrieMap.mergeMaybeSubset$1(HashMap.scala:748)
	at scala.collection.immutable.HashMap$HashTrieMap.merge0(HashMap.scala:876)
	at scala.collection.immutable.HashMap$HashTrieMap.mergeMaybeSubset$1(HashMap.scala:748)
	at scala.collection.immutable.HashMap$HashTrieMap.merge0(HashMap.scala:877)
	at scala.collection.immutable.HashMap.merged(HashMap.scala:137)
	at scala.collection.immutable.HashMap.$plus$plus(HashMap.scala:184)
	at scala.collection.immutable.HashMap.$plus$plus(HashMap.scala:173)
	at com.daml.platform.sandbox.stores.InMemoryActiveLedgerState.divulgeAlreadyCommittedContracts(InMemoryActiveLedgerState.scala:138)
	at com.daml.platform.sandbox.stores.InMemoryActiveLedgerState.divulgeAlreadyCommittedContracts(InMemoryActiveLedgerState.scala:21)
	at com.daml.platform.store.ActiveLedgerStateManager.$anonfun$addTransaction$15(ActiveLedgerStateManager.scala:220)
	at scala.Option.map(Option.scala:230)
	at com.daml.platform.store.ActiveLedgerStateManager$AddTransactionState.mapAcs(ActiveLedgerStateManager.scala:34)
	at com.daml.platform.store.ActiveLedgerStateManager.addTransaction(ActiveLedgerStateManager.scala:220)
	at com.daml.platform.sandbox.stores.InMemoryActiveLedgerState.addTransaction(InMemoryActiveLedgerState.scala:167)
	at com.daml.platform.sandbox.stores.ledger.inmemory.InMemoryLedger.$anonfun$handleSuccessfulTx$2(InMemoryLedger.scala:323)
	at com.daml.platform.sandbox.stores.ledger.inmemory.InMemoryLedger.$anonfun$handleSuccessfulTx$2$adapted(InMemoryLedger.scala:307)
	at scala.util.Either.fold(Either.scala:191)
	at com.daml.platform.sandbox.stores.ledger.inmemory.InMemoryLedger.handleSuccessfulTx(InMemoryLedger.scala:307)
	at com.daml.platform.sandbox.stores.ledger.inmemory.InMemoryLedger.publishTransaction(InMemoryLedger.scala:282)
	at com.daml.platform.sandbox.stores.ledger.MeteredLedger.$anonfun$publishTransaction$1(MeteredLedger.scala:27)
	at com.daml.metrics.Timed$.future(Timed.scala:30)
	at com.daml.platform.sandbox.stores.ledger.MeteredLedger.publishTransaction(MeteredLedger.scala:27)
	at com.daml.platform.sandbox.stores.LedgerBackedWriteService.submitTransaction(SandboxIndexAndWriteService.scala:180)
	at com.daml.ledger.participant.state.v1.metrics.TimedWriteService.$anonfun$submitTransaction$1(TimedWriteService.scala:23)
	at com.daml.metrics.Timed$.completionStage(Timed.scala:22)
	at com.daml.ledger.participant.state.v1.metrics.TimedWriteService.submitTransaction(TimedWriteService.scala:23)
	at com.daml.platform.apiserver.services.ApiSubmissionService.submitTransaction(ApiSubmissionService.scala:268)
	at com.daml.platform.apiserver.services.ApiSubmissionService.submitTransaction(ApiSubmissionService.scala:251)
	at com.daml.platform.apiserver.services.ApiSubmissionService.$anonfun$recordOnLedger$5(ApiSubmissionService.scala:203)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:47)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:47)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by SamirTalwar-DA** [comment]
Hey @dsun-da. Sorry for the delay on this. Is this still reproducible with the latest snapshot?

If it is, can you share (publicly or privately) the code that causes it?

**Comment by dsun-da** [comment]
@SamirTalwar Unfortunately this is not reproducible. I have only observed this once running in CI.

**Comment by SamirTalwar-DA** [comment]
OK, I see. Which version of Sandbox Classic were you using when you saw the error?

**Comment by SamirTalwar-DA** [comment]
For reference, this was using Sandbox Classic version 1.2.0-snapshot.20200513.4172.0.021f4af3.

Closing as we can't reproduce it. Let's re-open this if it comes up again.

**Comment by jberthold-da** [comment]
We are observing the same null pointer exception (identical stack trace) in a nightly end-to-end test. This looks fairly well-reproducible, but it involves large amounts of data, I was unable to observe it with less.
Will share details privately

**Comment by mziolekda** [comment]
Problem reported on discontinued product line
