### ISSUE TITLE
daml assistant: Reading from input files fails with non-ASCII characters.

### ISSUE THREAD

**Issue by hyperfekt** [digital-asset/daml#6338]
When trying to run `daml script` with an input file in UTF-8 encoding that contains non-ASCII characters in a `Text`-typed field, it prints the following to the console and does nothing else (but doesn't exit either):
```
Exception in thread "main" java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.read1(BufferedReader.java:210)
	at java.io.BufferedReader.read(BufferedReader.java:286)
	at java.io.Reader.read(Reader.java:140)
	at scala.io.BufferedSource.mkString(BufferedSource.scala:98)
	at com.daml.lf.engine.script.RunnerMain$.$anonfun$main$3(RunnerMain.scala:71)
	at scala.Option.map(Option.scala:230)
	at com.daml.lf.engine.script.RunnerMain$.main(RunnerMain.scala:68)
	at com.daml.sdk.SdkMain$.main(SdkMain.scala:21)
	at com.daml.sdk.SdkMain.main(SdkMain.scala)
```
DAML version: `1.2.0-snapshot.20200527.4268.0.acc5a21c`

**Comment by cocreature** [comment]
Hi @hyperfekt, thanks for the bug report! I tried to reproduce this with an input file containing `"aαλξbc"` and script that simply has a `Text` argument but I was unable to do so. Could you provide the input file and the script that caused this issue for you? Thanks!

**Comment by hyperfekt** [comment]
The issue should e reproducible by running the `Setup:submitChoice` script from the [contracts-for-tshirts repository](https://github.com/digital-asset/contracts-for-tshirts/tree/431c1f6c69581bfaa73737afef1edeb04e771dd2), and changing `Alice` to `Älice` in the `submit.json` file.

**Comment by cocreature** [comment]
I’ve tried changing `submit.json` as follows
```
{
  "parties" : {
    "submitter" : "Alice::015a7c0698d08ab22b3f401e51e6849d58c2258ad34a18dc9a4abadb81be5d9949",
    "organizer" : "freeshirts::01416588161bd9e1ecec1295a6358576b109f6e3cd985e22e92014d02e5757d48c"
  },
  "order" : {
    "shirtChoice" : "DAMLShirt",
    "shirtSize" : "L",
    "address" : {
      "firstname" : "Älice",
      "lastname" : "Wonderland",
      "streetAddress" : "Humpty Dumpty Street 12",
      "zipCode" : "1234",
      "city" : "Rapperswil",
      "country" : "CH",
      "email" : "alice@wonderland.ch"
    }
  }
}
```
However, that still works for me. Which OS are you using and which locale?

**Comment by hyperfekt** [comment]
That was it. I had selected a nonexistent locale in KDE (please don't ask me why that is possible in the first place), so DAML fell back to the `C` one, which does not support UTF-8.

**Comment by cocreature** [comment]
Glad you got it working! I’ll see if we can just always default to utf-8. Reading files depending on locale is almost never useful ime.
