### ISSUE TITLE
sandbox-next throws "INTERNAL: Failed to parse submission"

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#6494]
I ran the following DAML Script against both Sandbox-next and sandbox-classic:
```
module Main where

import Daml.Script

data RList a = Nil | Cons {value: a, next: RList a} deriving (Eq, Show)

createRList : Int -> Text -> RList Text
createRList 0 t = Nil
createRList i t = Cons {value=(t<>show i), next=(createRList (i-1) t)}

template TList
  with
    owner: Party
    value: RList Text
  where
    signatory owner

    controller owner can
      Append: ContractId TList
        with
          newValue : Text
        do
          create TList with owner; value = Cons {value=newValue, next=value}

example = do
  p <- allocateParty "p"
  submit p do
      createCmd TList with
        owner = p
        value = createRList 45 "X"
```

This works fine with sandbox-classic but sandbox-next fails with the following error:
```
ERROR: Unhandled internal error (context: {commandId=5b3dfbb8-787b-48b3-aef8-958f042a1b69, parties=[party-517311ea]})
io.grpc.StatusRuntimeException: INTERNAL: Failed to parse submission, correlationId=5b3dfbb8-787b-48b3-aef8-958f042a1b69
        at io.grpc.Status.asRuntimeException(Status.java:524)
        at com.daml.platform.apiserver.services.ApiSubmissionService.mapSubmissionResult(ApiSubmissionService.scala:175)
        at com.daml.platform.apiserver.services.ApiSubmissionService.$anonfun$deduplicateAndRecordOnLedger$2(ApiSubmissionService.scala:127)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:47)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:47)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
WARN: Service responded with error for submitting command with context (Future(<not completed>),5b3dfbb8-787b-48b3-aef8-958f042a1b69). Status of command is unknown. watching for completion...
io.grpc.StatusRuntimeException: INTERNAL: Failed to parse submission, correlationId=5b3dfbb8-787b-48b3-aef8-958f042a1b69
        at io.grpc.Status.asRuntimeException(Status.java:524)
        at com.daml.platform.apiserver.services.ApiSubmissionService.mapSubmissionResult(ApiSubmissionService.scala:175)
        at com.daml.platform.apiserver.services.ApiSubmissionService.$anonfun$deduplicateAndRecordOnLedger$2(ApiSubmissionService.scala:127)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:47)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:47)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

I’ve built this against current HEAD.

**Comment by cocreature** [comment]
Also fails on 1.0.0.

**Comment by cocreature** [comment]
Here’s an example that’s even more minimal:
```
module Main where

import Daml.Script

data Nat = Z | Succ Nat deriving (Eq, Show)

toNat : Int -> Nat
toNat 0 = Z
toNat i = Succ (toNat (i - 1))

template T
  with
    p : Party
    v : Nat
  where
    signatory p

example = do
  p <- allocateParty "p"
  submit p do
    -- On 1.2.0 43 passes but 44 fails. Might be versin specific  
    createCmd (T p (toNat 44))
```

**Comment by gerolf-da** [comment]
A first hypothesis is that this has to do with value/recursion depth?

**Comment by cocreature** [comment]
@gerolf-da yeah that seems to be the case. As mentioned in the last example, if I decrease it to 43 it works. I thought we set the protobuf recursion limits much higher than 44 so not really sure where this is failing.

**Comment by gerolf-da** [comment]
So set the recursion limit to 1000 for reading packages. This error happens when [unpacking submissions in kvutils](https://github.com/digital-asset/daml/blob/master/ledger/participant-state/kvutils/src/main/scala/com/daml/ledger/participant/state/kvutils/Envelope.scala#L88).

**Comment by gerolf-da** [comment]
The default recursion limit in `CodedInputStream` is 100, so probably we go beyond that with a `Nat` of `44`.

**Comment by mziolekda** [comment]
Closing, sandbox-next no longer exists
