### ISSUE TITLE
[Feature request] Add flag to run sandbox/sandbox-classic without write sandbox.log into filesystem

### ISSUE THREAD

**Issue by lima-da** [digital-asset/daml#6888]
DABL is currently switching to use official DAML SDK to run sandbox on the cloud now. However, for safety reason, we only allow read permission for the container to run the sandbox. The sandbox starts fine without write permission to the disk but seeing this error: 
```21:42:51,609 |-ERROR in ch.qos.logback.core.FileAppender[FILE] - openFile(sandbox.log,true) call failed. java.io.FileNotFoundException: sandbox.log (Read-only file system)
        at java.io.FileNotFoundException: sandbox.log (Read-only file system)
        at      at java.io.FileOutputStream.open0(Native Method)
        at      at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at      at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at      at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)
        at      at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:204)
        at      at ch.qos.logback.core.FileAppender.start(FileAppender.java:127)
        at      at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:90)
        at      at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
        at      at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
        at      at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
        at      at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
        at      at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
        at      at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
        at      at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
        at      at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
        at      at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
        at      at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
        at      at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
        at      at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
        at      at com.daml.platform.sandbox.GlobalLogLevel$.set(GlobalLogLevel.scala:11)
        at      at com.daml.platform.sandbox.SandboxMain$.$anonfun$main$2(SandboxMain.scala:17)
        at      at com.daml.platform.sandbox.SandboxMain$.$anonfun$main$2$adapted(SandboxMain.scala:17)
        at      at scala.Option.foreach(Option.scala:407)
        at      at com.daml.platform.sandbox.SandboxMain$.main(SandboxMain.scala:17)
        at      at com.daml.sdk.SdkMain$.main(SdkMain.scala:30)
        at      at com.daml.sdk.SdkMain.main(SdkMain.scala)
```

Would be great to have a flag to turn log writing off on sandbox start.

**Comment by cocreature** [comment]
You should be able to configure that in the logback file, see https://github.com/digital-asset/daml/blob/master/ledger/sandbox-common/src/main/resources/logback.xml#L10. https://discuss.daml.com/t/how-can-i-make-debug-statements-visible-in-the-sandbox-logs/478/2?u=cocreature explains how you can change the logback file which is a bit tricky if you don’t invoke the JAR directly. Note that starting from 1.4.0, there will be a standalone JAR for daml-on-sql so this becomes a lot easier.

**Comment by lima-da** [comment]
@cocreature Thanks for the info! that's really helpful does the daml-on-sql standalone JAR has its own docker image that we can run directly? or it's just on maven repo?

**Comment by cocreature** [comment]
It will be published as a fat JAR on github releases. No plans for an open source docker image atm.

**Comment by lima-da** [comment]
Thanks @cocreature I will close this issue.
