### ISSUE TITLE
DAML Script appears to incorrectly parse parameters for client certs

### ISSUE THREAD

**Issue by nycnewman** [digital-asset/daml#7053]
When running command:

daml script --dar .daml/dist/ex-secure-daml-infra-0.0.1.dar --script-name Setup:initialize --ledger-host server.acme.com --ledger-port 6865 --access-token-file=./certs/jwt/script.token --tls --pem /Users/edwardnewman/src/ex-secure-daml-infra/certs/client/client1.acme.com.key.pem --crt /Users/edwardnewman/src/ex-secure-daml-infra/certs/client/client1.acme.com.cert.pem --cacrt /Users/edwardnewman/src/ex-secure-daml-infra/certs/intermediate/certs/ca-chain.cert.pem

The following error is thrown (stacktrace truncated):

Exception in thread "main" java.lang.IllegalArgumentException: File does not contain valid private key: /Users/edwardnewman/src/ex-secure-daml-infra/certs/client/client1.acme.com.cert.pem
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:350)
Caused by: java.security.KeyException: could not find a PKCS #8 private key in input stream (see https://netty.io/wiki/sslcontextbuilder-and-private-key.html for more information)

Error message references the certificate file not the private key file passed as a parameter.

Reversing parameters produces

+ daml script --dar .daml/dist/ex-secure-daml-infra-0.0.1.dar --script-name Setup:initialize --ledger-host server.acme.com --ledger-port 6865 --access-token-file=./certs/jwt/script.token --tls --pem /Users/edwardnewman/src/ex-secure-daml-infra/certs/client/client1.acme.com.cert.pem --crt /Users/edwardnewman/src/ex-secure-daml-infra/certs/client/client1.acme.com.key.pem --cacrt /Users/edwardnewman/src/ex-secure-daml-infra/certs/intermediate/certs/ca-chain.cert.pem
Reading token from ./certs/jwt/script.token...
Reading token from ./certs/jwt/script.token...
Exception in thread "main" java.lang.IllegalArgumentException: Either both keyCertChain and key needs to be null or none of them
	at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext.newSessionContext(ReferenceCountedOpenSslClientContext.java:94)

daml script fails to execute script due to failure.

**Comment by nycnewman** [comment]
Note also that daml script also hangs on TLS errors and never exits

**Comment by cocreature** [comment]
Thanks for the issue! I noticed that myself a few days ago and fixed it in https://github.com/digital-asset/daml/commit/5ceeb476c8e85b6bbd20f4351ba487f083725a24. The fix is included in the [latest snapshot](https://github.com/digital-asset/daml/releases/tag/v1.5.0-snapshot.20200804.4902.0.de2fef6b).
