### ISSUE TITLE
Error when trying to submit commands to sandbox-classic on Postgres

### ISSUE THREAD

**Issue by da-tanabe** [digital-asset/daml#7470]
The specific command is actually just exercising 1,000 "Archive" choices on a contract, and Sandbox Classic (DAML SDK 1.5) on Postgres is failing with an error I've never seen before: 

```
WARN: daml.index.db.connection.sandbox - Connection org.postgresql.jdbc.PgConnection@56c6cf6 marked as broken because of SQLSTATE(08006), ErrorCode(0)
org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:337)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at anorm.Sql.$anonfun$resultSet$2(Anorm.scala:104)
	at resource.DefaultManagedResource.open(AbstractManagedResource.scala:110)
	at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:87)
	at resource.ManagedResourceOperations$$anon$2.$anonfun$acquireFor$1(ManagedResourceOperations.scala:49)
	at resource.AbstractManagedResource.$anonfun$acquireFor$1(AbstractManagedResource.scala:88)
	at scala.util.control.Exception$Catch.$anonfun$either$1(Exception.scala:252)
	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
	at scala.util.control.Exception$Catch.either(Exception.scala:252)
	at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:88)
	at resource.ManagedResourceOperations$$anon$2.acquireFor(ManagedResourceOperations.scala:49)
	at resource.DeferredExtractableManagedResource.acquireFor(AbstractManagedResource.scala:27)
	at resource.ManagedResourceOperations.apply(ManagedResourceOperations.scala:26)
	at resource.ManagedResourceOperations.apply$(ManagedResourceOperations.scala:26)
	at resource.DeferredExtractableManagedResource.apply(AbstractManagedResource.scala:24)
	at resource.ManagedResourceOperations.acquireAndGet(ManagedResourceOperations.scala:25)
	at resource.ManagedResourceOperations.acquireAndGet$(ManagedResourceOperations.scala:25)
	at resource.DeferredExtractableManagedResource.acquireAndGet(AbstractManagedResource.scala:24)
	at anorm.Sql$.$anonfun$asTry$1(Anorm.scala:228)
	at scala.util.Try$.apply(Try.scala:213)
	at anorm.Sql$.asTry(Anorm.scala:228)
	at anorm.WithResult.asTry(SqlResult.scala:181)
	at anorm.WithResult.asTry$(SqlResult.scala:181)
	at anorm.SimpleSql.asTry(SimpleSql.scala:6)
	at anorm.WithResult.as(SqlResult.scala:173)
	at anorm.WithResult.as$(SqlResult.scala:172)
	at anorm.SimpleSql.as(SimpleSql.scala:6)
	at com.daml.platform.store.dao.JdbcLedgerDao.$anonfun$getParties$1(JdbcLedgerDao.scala:569)
	at com.daml.platform.store.dao.HikariJdbcConnectionProvider.$anonfun$runSQL$1(HikariJdbcConnectionProvider.scala:131)
	at com.daml.metrics.Timed$.$anonfun$value$1(Timed.scala:18)
	at com.codahale.metrics.Timer.time(Timer.java:118)
	at com.daml.metrics.Timed$.value(Timed.scala:18)
	at com.daml.platform.store.dao.HikariJdbcConnectionProvider.runSQL(HikariJdbcConnectionProvider.scala:131)
	at com.daml.platform.store.dao.DbDispatcher.$anonfun$executeSql$2(DbDispatcher.scala:53)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Tried to send an out-of-range integer as a 2-byte value: 39820
	at org.postgresql.core.PGStream.sendInteger2(PGStream.java:266)
	at org.postgresql.core.v3.QueryExecutorImpl.sendParse(QueryExecutorImpl.java:1500)
	at org.postgresql.core.v3.QueryExecutorImpl.sendOneQuery(QueryExecutorImpl.java:1823)
	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1386)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:302)
	... 49 common frames omitted
ERROR: Exception while executing SQL query. Rolled back. (context: {parties=[…], submittedAt=2020-09-23T15:17:14.402Z, applicationId=…, deduplicateUntil=2020-09-24T15:17:14.402Z, participantId=sandbox-participant, metric=load_parties, submitter=…, commandId=b5ddfc89-65ca-4707-b1d5-ae759277a63f, workflowId=5f7182e1-8b4a-4d23-8459-e02593249ff2})
java.sql.SQLException: Connection is closed
	at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:489)
	at com.sun.proxy.$Proxy3.rollback(Unknown Source)
	at com.zaxxer.hikari.pool.ProxyConnection.rollback(ProxyConnection.java:370)
	at com.zaxxer.hikari.pool.HikariProxyConnection.rollback(HikariProxyConnection.java)
	at com.daml.platform.store.dao.HikariJdbcConnectionProvider.runSQL(HikariJdbcConnectionProvider.scala:144)
	at com.daml.platform.store.dao.DbDispatcher.$anonfun$executeSql$2(DbDispatcher.scala:53)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by gerolf-da** [comment]
Could you put this in small DAML project (that reproduces the issue) and upload it here?

**Comment by gerolf-da** [comment]
Thanks Davin. This is now tracked by KVL-540.
