### ISSUE TITLE
//ledger/ledger-api-test-tool:ledger-api-test-tool-test flaky on master

### ISSUE THREAD

**Issue by garyverhaegen-da** [digital-asset/daml#815]
[This build](https://dev.azure.com/digitalasset/daml/_build/results?buildId=3922) failed on master with a timeout, and worked when reran. Tests on master should be stable.

@gleber-da @dajmaki @meiersi-da please find the right person to assign this ticket.

**Comment by gleber-da** [comment]
I have done couple of times
```
$ git log --pretty=format:"%h%x09%an%x09%ad%x09%s" -1
b0478bbd        Moritz Kiefer   Thu May 2 10:22:06 2019 +0200   Fix permissions in "daml new" (#827)
$ bazel test --runs_per_test=100 //ledger/ledger-api-test-tool:ledger-api-test-tool-test
```
and eventually got
```
failure: Status{code=ABORTED, description=The maximum record time of the command exceeded, cause=null}
Exception in thread "main" java.lang.RuntimeException: Running scenario Test:authorization_success2_delegation failed with: The code property had value 10, instead of its expected value 0, on object Status(10,The maximum record time of the command exceeded,List()),
inside Completion(semantic-testing-Test:authorization_success2_delegation-0-NodeId(0:0),Some(Status(10,The maximum record time of the command exceeded,List())),None)

With stacktrace:
org.scalatest.exceptions.TestFailedException: The code property had value 10, instead of its expected value 0, on object Status(10,The maximum record time of the command exceeded,List()),
inside Completion(semantic-testing-Test:authorization_success2_delegation-0-NodeId(0:0),Some(Status(10,The maximum record time of the command exceeded,List())),None)
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:346)
	at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
	at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
	at com.digitalasset.platform.tests.integration.ledger.api.LedgerTestingHelpers$$anonfun$assertCompletionIsSuccessful$1.applyOrElse(LedgerTestingHelpers.scala:51)
	at com.digitalasset.platform.tests.integration.ledger.api.LedgerTestingHelpers$$anonfun$assertCompletionIsSuccessful$1.applyOrElse(LedgerTestingHelpers.scala:51)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at org.scalatest.Inside.inside(Inside.scala:128)
	at org.scalatest.Inside.inside$(Inside.scala:103)
	at com.digitalasset.platform.tests.integration.ledger.api.LedgerTestingHelpers.inside(LedgerTestingHelpers.scala:34)
	at com.digitalasset.platform.tests.integration.ledger.api.LedgerTestingHelpers.assertCompletionIsSuccessful(LedgerTestingHelpers.scala:51)
	at com.digitalasset.platform.tests.integration.ledger.api.LedgerTestingHelpers.$anonfun$submitSuccessfully$2(LedgerTestingHelpers.scala:48)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)


Testing tool own stacktrace is:
	at scala.sys.package$.error(package.scala:27)
	at com.daml.ledger.api.testtool.LedgerApiTestTool$.$anonfun$main$8(LedgerApiTestTool.scala:86)
	at com.daml.ledger.api.testtool.LedgerApiTestTool$.$anonfun$main$8$adapted(LedgerApiTestTool.scala:72)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at com.daml.ledger.api.testtool.LedgerApiTestTool$.$anonfun$main$5(LedgerApiTestTool.scala:72)
	at com.daml.ledger.api.testtool.LedgerApiTestTool$.$anonfun$main$5$adapted(LedgerApiTestTool.scala:65)
	at scala.collection.immutable.Map$Map3.foreach(Map.scala:192)
	at com.daml.ledger.api.testtool.LedgerApiTestTool$.main(LedgerApiTestTool.scala:65)
	at com.daml.ledger.api.testtool.LedgerApiTestTool.main(LedgerApiTestTool.scala)
runner: callProcess: ledger/ledger-api-test-tool/ledger-api-test-tool "--target-port" "36553" (exit 1): failed

```
