### ISSUE TITLE
daml repl doesn't recover when a non-terminating function fails

### ISSUE THREAD

**Issue by anthonylusardi-da** [digital-asset/daml#8901]
Inspired by [György](https://discuss.daml.com/t/an-endless-lit-makes-the-repl-work-for-a-long-time-and-this-is-intentional-updated-title/2116) and [Bernhard's](https://discuss.daml.com/t/an-endless-lit-makes-the-repl-work-for-a-long-time-and-this-is-intentional-updated-title/2116/10?u=anthony) posts on non-terminating/long running functions in Daml in general and specifically in the REPL I decided to see what would actually happen if I ran György's code.

Expected behavior: REPL should either fail completely or give me back a usable terminal
Actual behavior: REPL fails and is left in an odd state where it gives me a terminal that doesn't accept input

Steps to repeat:

1. Run `take 3 [1..]` or any long running function
1. REPL appears to return to console without any output (but started ignoring any input)
1. Obvious a process was still running because my laptop fan was going wild
1. Get `java.lang.OutOfMemoryError: Java heap space` error
1. Get a terminal where I couldn't actually run any commands

RE point 2 above, it's deceptive in the output below but the line `daml> Uncaught error...` actually was `daml> ` before the heap blew up and started printing to the terminal.

```
$ daml repl
daml> take 3 [1..]
daml> Uncaught error from thread [Repl-akka.actor.default-dispatcher-11]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[Repl]
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3690)
	at java.base/java.util.ArrayList.grow(ArrayList.java:237)
	at java.base/java.util.ArrayList.grow(ArrayList.java:242)
	at java.base/java.util.ArrayList.add(ArrayList.java:485)
	at java.base/java.util.ArrayList.add(ArrayList.java:498)
	at com.daml.lf.speedy.Speedy$KPushTo.execute(Speedy.scala:1130)
	at com.daml.lf.speedy.Speedy$Machine.run(Speedy.scala:391)
	at com.daml.lf.engine.script.Runner.stepToValue$1(Runner.scala:465)
	at com.daml.lf.engine.script.Runner.$anonfun$runWithClients$64(Runner.scala:829)
	at com.daml.lf.engine.script.Runner$$Lambda$903/0x000000080179f040.apply(Unknown Source)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.Future$$Lambda$273/0x0000000801409840.apply(Unknown Source)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.Promise$$Lambda$274/0x000000080140a840.apply(Unknown Source)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$Lambda$271/0x00000008013f0c40.apply$mcV$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

daml> take 3 [1..]
daml> take 3 [1,2,3,4]
daml> 
```

**Comment by dylant-da** [comment]
It now reports a `BErrorClient (ClientIOError GRPCIOTimeout)`.

Still, I agree that this is still less than ideal - added to backlog, will work on it moving forward.

```
daml> 
daml> take 3 [1,2,3,4]
[1,2,3]
daml> take 3 [1..]
BErrorClient (ClientIOError (GRPCIOBadStatusCode StatusDeadlineExceeded (StatusDetails {unStatusDetails = "Deadline Exceeded"})))
daml> Uncaught error from thread [Repl-akka.actor.default-dispatcher-19]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[Repl]
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3689)
	at java.base/java.util.ArrayList.grow(ArrayList.java:238)
	at java.base/java.util.ArrayList.grow(ArrayList.java:243)
	at java.base/java.util.ArrayList.add(ArrayList.java:486)
	at java.base/java.util.ArrayList.add(ArrayList.java:499)
	at com.daml.lf.speedy.Speedy$KPushTo.execute(Speedy.scala:1547)
	at com.daml.lf.speedy.Speedy$KPushTo.execute(Speedy.scala:1535)
	at com.daml.lf.speedy.Speedy$Machine.loop$1(Speedy.scala:833)
	at com.daml.lf.speedy.Speedy$Machine.run(Speedy.scala:844)
	at com.daml.lf.engine.script.Runner.stepToValue$1(Runner.scala:438)
	at com.daml.lf.engine.script.Runner.$anonfun$runWithClients$13(Runner.scala:531)
	at com.daml.lf.engine.script.Runner$$Lambda$1080/0x00000008406ed840.apply(Unknown Source)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$Lambda$268/0x00000008402bf840.apply$mcV$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

daml> take 3 [1,2,3,4]
BErrorClient (ClientIOError GRPCIOTimeout)
daml> take 3 [1,2,3,4,5]
BErrorClient (ClientIOError GRPCIOTimeout)
daml> take 3 [1..]
BErrorClient (ClientIOError GRPCIOTimeout)
daml> 
```

**Comment by moisesackerman-da** [comment]
With the `daml repl` removed (https://github.com/digital-asset/daml/issues/17373), this is no longer an issue.
